import {Injectable} from '@angular/core';
import {Pokemon} from '../interfaces/pokemon';
import {TypesEnum} from '../enums/types.enum';
import {HttpClient} from '@angular/common/http';
import {ColorEnum} from '../enums/color.enum';
import {StoneEnum} from '../enums/stone.enum';

@Injectable({
  providedIn: 'root'
})
export class AllPokemonService {
  public pokemonArray: Array<Pokemon> = [
    {
      id: 1,
      name: 'Bulbasaur',
      evolutionLevel: 16,
      types: [TypesEnum.grass],
      height: '0.7 m',
      weight: '6.9 kg',
      taux: 125,
      color: [ColorEnum.grassColor],
      img: './assets/images/Bulbasaur.png',
      icon: './assets/icons/Bulbasaur.png',
      audio: './assets/audio/Bulbasaur.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 2,
      name: 'Ivysaur',
      evolutionLevel: 32,
      types: [TypesEnum.grass],
      height: '1.0 m',
      weight: '13 kg',
      taux: 32,
      color: [ColorEnum.grassColor],
      img: './assets/images/Ivysaur.png',
      icon: './assets/icons/Ivysaur.png',
      audio: './assets/audio/Ivysaur.ogg',
      attacks: [' Vine Whip', 'Razor Leaf', ' Seed Bomb', 'Solar Beam'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 3,
      name: 'Venusaur',
      types: [TypesEnum.grass],
      height: '2.0 m',
      weight: '100.0 kg',
      taux: 14,
      color: [ColorEnum.grassColor],
      img: './assets/images/Venusaur.png',
      icon: './assets/icons/Venusaur.png',
      audio: './assets/audio/Venusaur.ogg',
      attacks: [' Vine Whip', 'Razor Leaf', ' Seed Bomb', 'Solar Beam'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 4,
      name: 'Charmander',
      evolutionLevel: 16,
      types: [TypesEnum.fire],
      height: '0.6 m',
      weight: '8.5 kg',
      taux: 128,
      color: [ColorEnum.fireColor],
      img: './assets/images/Charmander.png',
      icon: './assets/icons/Charmander.png',
      audio: './assets/audio/Charmander.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 5,
      name: 'Charmeleon',
      evolutionLevel: 32,
      types: [TypesEnum.fire],
      height: '1.1 m',
      weight: '19.0 kg',
      taux: 66,
      color: [ColorEnum.fireColor],
      img: './assets/images/Charmeleon.png',
      icon: './assets/icons/Charmeleon.png',
      audio: './assets/audio/Charmeleon.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 6,
      name: 'Charizard',
      types: [TypesEnum.fire],
      height: '1.7 m',
      weight: '90.5 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Charizard.png',
      icon: './assets/icons/Charizard.png',
      audio: './assets/audio/Charizard.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 7,
      name: 'Squirtle',
      evolutionLevel: 16,
      types: [TypesEnum.water],
      height: '0.5 m',
      weight: '9.0 kg ',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Squirtle.png',
      icon: './assets/icons/Squirtle.png',
      audio: './assets/audio/Squirtle.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 8,
      name: 'Wartortle',
      evolutionLevel: 32,
      types: [TypesEnum.water],
      height: '1.0 m',
      weight: '22.5 kg ',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Wartortle.png',
      icon: './assets/icons/Wartortle.png',
      audio: './assets/audio/Wartortle.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 9,
      name: 'Blastoise',
      types: [TypesEnum.water],
      height: '1.6m',
      weight: '85.5 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Blastoise.png',
      icon: './assets/icons/Blastoise.png',
      audio: './assets/audio/Blastoise.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 10,
      name: 'Caterpie',
      evolutionLevel: 7,
      types: [TypesEnum.bug],
      height: '0.3 m',
      weight: '2.9 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Caterpie.png',
      icon: './assets/icons/Caterpie.png',
      audio: './assets/audio/Caterpie.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 11,
      name: 'Metapod',
      evolutionLevel: 10,
      types: [TypesEnum.bug],
      height: '0.7 m',
      weight: '9.9 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Metapod.png',
      icon: './assets/icons/Metapod.png',
      audio: './assets/audio/Metapod.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 12,
      name: 'Butterfree',
      types: [TypesEnum.bug],
      height: '1.1 m',
      weight: '32.0 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Butterfree.png',
      icon: './assets/icons/Butterfree.png',
      audio: './assets/audio/Butterfree.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 13,
      name: 'Weedle',
      evolutionLevel: 7,
      types: [TypesEnum.bug],
      height: '0.3 m',
      weight: '3.2 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Weedle.png',
      icon: './assets/icons/Weedle.png',
      audio: './assets/audio/Weedle.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 14,
      name: 'Kakuna',
      evolutionLevel: 10,
      types: [TypesEnum.bug],
      height: '0.6 m',
      weight: '10.0 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Kakuna.png',
      icon: './assets/icons/Kakuna.png',
      audio: './assets/audio/Kakuna.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 15,
      name: 'Beedrill',
      types: [TypesEnum.bug],
      height: '1.0 m',
      weight: '29.5 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Beedrill.png',
      icon: './assets/icons/Beedrill.png',
      audio: './assets/audio/Beedrill.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 16,
      name: 'Pidgey',
      evolutionLevel: 18,
      types: [TypesEnum.flying],
      height: '0.3 m',
      weight: '1.8 kg',
      taux: 125,
      color: [ColorEnum.flyingColor],
      img: './assets/images/Pidgey.png',
      icon: './assets/icons/Pidgey.png',
      audio: './assets/audio/Pidgey.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 17,
      name: 'Pidgeotto',
      evolutionLevel: 36,
      types: [TypesEnum.flying],
      height: '1.1 m',
      weight: '30.0 kg',
      taux: 125,
      color: [ColorEnum.flyingColor],
      img: './assets/images/Pidgeotto.png',
      icon: './assets/icons/Pidgeotto.png',
      audio: './assets/audio/Pidgeotto.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 18,
      name: 'Pidgeot',
      types: [TypesEnum.flying],
      height: '1.5 m',
      weight: '39.5 kg',
      taux: 125,
      color: [ColorEnum.flyingColor],
      img: './assets/images/Pidgeot.png',
      icon: './assets/icons/Pidgeot.png',
      audio: './assets/audio/Pidgeot.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 19,
      name: 'Rattata',
      evolutionLevel: 20,
      types: [TypesEnum.normal],
      height: '0.3 m',
      weight: '3.5 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Rattata.png',
      icon: './assets/icons/Rattata.png',
      audio: './assets/audio/Rattata.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 20,
      name: 'Raticate',
      types: [TypesEnum.normal],
      height: '0.7 m',
      weight: '18.5 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Raticate.png',
      icon: './assets/icons/Raticate.png',
      audio: './assets/audio/Raticate.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 21,
      name: 'Spearow',
      evolutionLevel: 20,
      types: [TypesEnum.normal, TypesEnum.flying],
      height: '0.3 m',
      weight: '2.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.flyingColor],
      img: './assets/images/Spearow.png',
      icon: './assets/icons/Spearow.png',
      audio: './assets/audio/Spearow.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 22,
      name: 'Fearow',
      types: [TypesEnum.normal, TypesEnum.flying],
      height: '1.2 m',
      weight: '38.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.flyingColor],
      img: './assets/images/Fearow.png',
      icon: './assets/icons/Fearow.png',
      audio: './assets/audio/Fearow.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 23,
      name: 'Ekans',
      evolutionLevel: 22,
      types: [TypesEnum.poison],
      height: '2.0 m',
      weight: '6.9 kg',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Ekans.png',
      icon: './assets/icons/Ekans.png',
      audio: './assets/audio/Ekans.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 24,
      name: 'Arbok',
      types: [TypesEnum.poison],
      height: '3.5 m',
      weight: '65.0 kg',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Arbok.png',
      icon: './assets/icons/Arbok.png',
      audio: './assets/audio/Arbok.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 25,
      name: 'Pikachu',
      stone: [StoneEnum.thunder],
      types: [TypesEnum.electric],
      height: '0.4 m',
      weight: '6.0 kg',
      taux: 125,
      color: [ColorEnum.electricColor],
      img: './assets/images/Pikachu.png',
      icon: './assets/icons/Pikachu.png',
      audio: './assets/audio/Pikachu.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 26,
      name: 'Raichu',
      types: [TypesEnum.electric],
      height: '0.8 m',
      weight: '30.0 kg',
      taux: 125,
      color: [ColorEnum.electricColor],
      img: './assets/images/Raichu.png',
      icon: './assets/icons/Raichu.png',
      audio: './assets/audio/Raichu.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 27,
      name: 'Sandshrew',
      evolutionLevel: 22,
      types: [TypesEnum.ground],
      height: '0.6 m',
      weight: '12.0 kg ',
      taux: 125,
      color: [ColorEnum.groundColor],
      img: './assets/images/Sandshrew.png',
      icon: './assets/icons/Sandshrew.png',
      audio: './assets/audio/Sandshrew.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 28,
      name: 'Sandslash',
      types: [TypesEnum.ground],
      height: '1.0 m',
      weight: '29.5 kg ',
      taux: 125,
      color: [ColorEnum.groundColor],
      img: './assets/images/Sandslash.png',
      icon: './assets/icons/Sandslash.png',
      audio: './assets/audio/Sandslash.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 29,
      name: 'Nidoran♀',
      evolutionLevel: 16,
      types: [TypesEnum.poison],
      height: '0.4 m',
      weight: '7.0 kg',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Nidoran♀.png',
      icon: './assets/icons/Nidoran♀.png',
      audio: './assets/audio/Nidoran♀.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 30,
      name: 'Nidorina',
      stone: [StoneEnum.moon],
      types: [TypesEnum.poison],
      height: '0.7 m',
      weight: '6.9 kg',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Nidorina.png',
      icon: './assets/icons/Nidorina.png',
      audio: './assets/audio/Nidorina.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 31,
      name: 'Nidoqueen',
      types: [TypesEnum.poison, TypesEnum.ground],
      height: '1.3 m',
      weight: '60.0 kg',
      taux: 125,
      color: [ColorEnum.poisonColor, ColorEnum.groundColor],
      img: './assets/images/Nidoqueen.png',
      icon: './assets/icons/Nidoqueen.png',
      audio: './assets/audio/Nidoqueen.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 32,
      name: 'Nidoran♂',
      evolutionLevel: 16,
      types: [TypesEnum.poison],
      height: '0.5 m',
      weight: '9.0 kg',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Nidoran♂.png',
      icon: './assets/icons/Nidoran♂.png',
      audio: './assets/audio/Nidoran♂.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 33,
      name: 'Nidorino',
      stone: [StoneEnum.moon],
      types: [TypesEnum.poison],
      height: '0.9 m',
      weight: '19.5 kg',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Nidorino.png',
      icon: './assets/icons/Nidorino.png',
      audio: './assets/audio/Nidorino.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 34,
      name: 'Nidoking',
      types: [TypesEnum.poison, TypesEnum.ground],
      height: '1.4 m',
      weight: '62.0 kg',
      taux: 125,
      color: [ColorEnum.poisonColor, ColorEnum.groundColor],
      img: './assets/images/Nidoking.png',
      icon: './assets/icons/Nidoking.png',
      audio: './assets/audio/Nidoking.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 35,
      name: 'Clefairy',
      stone: [StoneEnum.moon],
      types: [TypesEnum.fairy],
      height: '0.6 m',
      weight: '7.5 kg ',
      taux: 125,
      color: [ColorEnum.fairyColor],
      img: './assets/images/Clefairy.png',
      icon: './assets/icons/Clefairy.png',
      audio: './assets/audio/Clefairy.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 36,
      name: 'Clefable',
      types: [TypesEnum.fairy],
      height: '1.3 m',
      weight: '40.0 kg ',
      taux: 125,
      color: [ColorEnum.fairyColor],
      img: './assets/images/Clefable.png',
      icon: './assets/icons/Clefable.png',
      audio: './assets/audio/Clefable.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 37,
      name: 'Vulpix',
      stone: [StoneEnum.fire],
      types: [TypesEnum.fire],
      height: '0.6 m',
      weight: '9.9 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Vulpix.png',
      icon: './assets/icons/Vulpix.png',
      audio: './assets/audio/Vulpix.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 38,
      name: 'Ninetales',
      types: [TypesEnum.fire],
      height: '1.1 m',
      weight: '19.9 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Ninetales.png',
      icon: './assets/icons/Ninetales.png',
      audio: './assets/audio/Ninetales.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 39,
      name: 'Jigglypuff',
      stone: [StoneEnum.moon],
      types: [TypesEnum.normal, TypesEnum.fairy],
      height: '0.5 m',
      weight: '5.5 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.fairyColor],
      img: './assets/images/Jigglypuff.png',
      icon: './assets/icons/Jigglypuff.png',
      audio: './assets/audio/Jigglypuff.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 40,
      name: 'Wigglytuff',
      types: [TypesEnum.normal, TypesEnum.fairy],
      height: '1.0 m',
      weight: '12.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.fairyColor],
      img: './assets/images/Wigglytuff.png',
      icon: './assets/icons/Wigglytuff.png',
      audio: './assets/audio/Wigglytuff.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 41,
      name: 'Zubat',
      evolutionLevel: 22,
      types: [TypesEnum.poison, TypesEnum.flying],
      height: '0.8 m',
      weight: '7.5 kg',
      taux: 125,
      color: [ColorEnum.poisonColor, ColorEnum.flyingColor],
      img: './assets/images/Zubat.png',
      icon: './assets/icons/Zubat.png',
      audio: './assets/audio/Zubat.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 42,
      name: 'Golbat',
      types: [TypesEnum.poison, TypesEnum.flying],
      height: '1.6 m',
      weight: '55.0 kg',
      taux: 125,
      color: [ColorEnum.poisonColor, ColorEnum.flyingColor],
      img: './assets/images/Golbat.png',
      icon: './assets/icons/Golbat.png',
      audio: './assets/audio/Golbat.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 43,
      name: 'Oddish',
      evolutionLevel: 21,
      types: [TypesEnum.grass, TypesEnum.poison],
      height: '0.5 m',
      weight: '5.4 kg ',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.poisonColor],
      img: './assets/images/Oddish.png',
      icon: './assets/icons/Oddish.png',
      audio: './assets/audio/Oddish.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 44,
      name: 'Gloom',
      stone: [StoneEnum.leaf],
      types: [TypesEnum.grass, TypesEnum.poison],
      height: '0.8 m',
      weight: '8.6 kg ',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.poisonColor],
      img: './assets/images/Gloom.png',
      icon: './assets/icons/Gloom.png',
      audio: './assets/audio/Gloom.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 45,
      name: 'Vileplume',
      types: [TypesEnum.grass, TypesEnum.poison],
      height: '1.2 m',
      weight: '18.6 kg',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.poisonColor],
      img: './assets/images/Vileplume.png',
      icon: './assets/icons/Vileplume.png',
      audio: './assets/audio/Vileplume.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 46,
      name: 'Paras',
      evolutionLevel: 24,
      types: [TypesEnum.bug, TypesEnum.grass],
      height: '0.3 m',
      weight: '5.4 kg',
      taux: 125,
      color: [ColorEnum.bugColor, ColorEnum.grassColor],
      img: './assets/images/Paras.png',
      icon: './assets/icons/Paras.png',
      audio: './assets/audio/Paras.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 47,
      name: 'Parasect',
      types: [TypesEnum.bug, TypesEnum.grass],
      height: '1.0 m',
      weight: '29.5 kg',
      taux: 125,
      color: [ColorEnum.bugColor, ColorEnum.grassColor],
      img: './assets/images/Parasect.png',
      icon: './assets/icons/Parasect.png',
      audio: './assets/audio/Parasect.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 48,
      name: 'Venonat',
      evolutionLevel: 31,
      types: [TypesEnum.bug, TypesEnum.poison],
      height: '1.0 m',
      weight: '30.0 kg',
      taux: 125,
      color: [ColorEnum.bugColor, ColorEnum.poisonColor],
      img: './assets/images/Venonat.png',
      icon: './assets/icons/Venonat.png',
      audio: './assets/audio/Venonat.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 49,
      name: 'Venomoth',
      types: [TypesEnum.bug, TypesEnum.poison],
      height: '1.5 m',
      weight: '12.5 kg',
      taux: 125,
      color: [ColorEnum.bugColor, ColorEnum.poisonColor],
      img: './assets/images/Venomoth.png',
      icon: './assets/icons/Venomoth.png',
      audio: './assets/audio/Venomoth.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 50,
      name: 'Diglett',
      evolutionLevel: 26,
      types: [TypesEnum.ground],
      height: '0.2 m',
      weight: '0.8 kg ',
      taux: 125,
      color: [ColorEnum.groundColor],
      img: './assets/images/Diglett.png',
      icon: './assets/icons/Diglett.png',
      audio: './assets/audio/Diglett.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 51,
      name: 'Dugtrio',
      types: [TypesEnum.ground],
      height: '0.7 m',
      weight: '33.3 kg ',
      taux: 125,
      color: [ColorEnum.groundColor],
      img: './assets/images/Dugtrio.png',
      icon: './assets/icons/Dugtrio.png',
      audio: './assets/audio/Dugtrio.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 52,
      name: 'Meowth',
      evolutionLevel: 28,
      types: [TypesEnum.normal],
      height: '0.4 m',
      weight: '4.2 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Meowth.png',
      icon: './assets/icons/Meowth.png',
      audio: './assets/audio/Meowth.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 53,
      name: 'Persian',
      types: [TypesEnum.normal],
      height: '1.0 m',
      weight: '32.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Persian.png',
      icon: './assets/icons/Persian.png',
      audio: './assets/audio/Persian.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 54,
      name: 'Psyduck',
      evolutionLevel: 33,
      types: [TypesEnum.water],
      height: '0.8 m',
      weight: '19.6 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Psyduck.png',
      icon: './assets/icons/Psyduck.png',
      audio: './assets/audio/Psyduck.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 55,
      name: 'Golduck',
      types: [TypesEnum.water],
      height: '1.7 m',
      weight: '76.6 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Golduck.png',
      icon: './assets/icons/Golduck.png',
      audio: './assets/audio/Golduck.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 56,
      name: 'Mankey',
      evolutionLevel: 28,
      types: [TypesEnum.fighting],
      height: '0.5 m',
      weight: '28.0 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Mankey.png',
      icon: './assets/icons/Mankey.png',
      audio: './assets/audio/Mankey.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 57,
      name: 'Primeape',
      types: [TypesEnum.fighting],
      height: '1.0 m',
      weight: '32.0 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Primeape.png',
      icon: './assets/icons/Primeape.png',
      audio: './assets/audio/Primeape.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 58,
      name: 'Growlithe',
      stone: [StoneEnum.fire],
      types: [TypesEnum.fire],
      height: '0.7 m',
      weight: '19.0 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Growlithe.png',
      icon: './assets/icons/Growlithe.png',
      audio: './assets/audio/Growlithe.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 59,
      name: 'Arcanine',
      types: [TypesEnum.fire],
      height: '1.9 m',
      weight: '155.0 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Arcanine.png',
      icon: './assets/icons/Arcanine.png',
      audio: './assets/audio/Arcanine.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 60,
      name: 'Poliwag',
      evolutionLevel: 25,
      types: [TypesEnum.water],
      height: '0.6 m',
      weight: '12.4 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Poliwag.png',
      icon: './assets/icons/Poliwag.png',
      audio: './assets/audio/Poliwag.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 61,
      name: 'Poliwhirl',
      stone: [StoneEnum.water],
      evolutionLevel: 16,
      types: [TypesEnum.water],
      height: '1.0 m',
      weight: '20.0 kg ',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Poliwhirl.png',
      icon: './assets/icons/Poliwhirl.png',
      audio: './assets/audio/Poliwhirl.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 62,
      name: 'Poliwrath',
      types: [TypesEnum.water, TypesEnum.fighting],
      height: '1.3 m',
      weight: '54.0 kg ',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.fightingColor],
      img: './assets/images/Poliwrath.png',
      icon: './assets/icons/Poliwrath.png',
      audio: './assets/audio/Poliwrath.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 63,
      name: 'Abra',
      evolutionLevel: 16,
      types: [TypesEnum.psychic],
      height: '0.9 m',
      weight: '19.5 kg',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Abra.png',
      icon: './assets/icons/Abra.png',
      audio: './assets/audio/Abra.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 64,
      name: 'Kadabra',
      exchange: true,
      types: [TypesEnum.psychic],
      height: '1.3 m',
      weight: '56.5 kg',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Kadabra.png',
      icon: './assets/icons/Kadabra.png',
      audio: './assets/audio/Kadabra.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 65,
      name: 'Alakazam',
      types: [TypesEnum.psychic],
      height: '1.5 m',
      weight: '48.0 kg',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Alakazam.png',
      icon: './assets/icons/Alakazam.png',
      audio: './assets/audio/Alakazam.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 66,
      name: 'Machop',
      evolutionLevel: 28,
      types: [TypesEnum.fighting],
      height: '0.8 m',
      weight: '19.5 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Machop.png',
      icon: './assets/icons/Machop.png',
      audio: './assets/audio/Machop.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 67,
      name: 'Machoke',
      exchange: true,
      types: [TypesEnum.fighting],
      height: '1.5 m',
      weight: '70.5 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Machoke.png',
      icon: './assets/icons/Machoke.png',
      audio: './assets/audio/Machoke.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 68,
      name: 'Machamp',
      types: [TypesEnum.fighting],
      height: '1.6 m',
      weight: '130.0 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Machamp.png',
      icon: './assets/icons/Machamp.png',
      audio: './assets/audio/Machamp.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 69,
      name: 'Bellsprout',
      evolutionLevel: 21,
      types: [TypesEnum.grass, TypesEnum.poison],
      height: '0.7 m',
      weight: '4.0 kg',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.poisonColor],
      img: './assets/images/Bellsprout.png',
      icon: './assets/icons/Bellsprout.png',
      audio: './assets/audio/Bellsprout.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 70,
      name: 'Weepinbell',
      stone: [StoneEnum.leaf],
      types: [TypesEnum.grass, TypesEnum.poison],
      height: '1.0 m',
      weight: '6.4 kg',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.poisonColor],
      img: './assets/images/Weepinbell.png',
      icon: './assets/icons/Weepinbell.png',
      audio: './assets/audio/Weepinbell.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 71,
      name: 'Victreebel',
      types: [TypesEnum.grass, TypesEnum.poison],
      height: '1.7 m',
      weight: '15.5 kg',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.poisonColor],
      img: './assets/images/Victreebel.png',
      icon: './assets/icons/Victreebel.png',
      audio: './assets/audio/Victreebel.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 72,
      name: 'Tentacool',
      evolutionLevel: 30,
      types: [TypesEnum.water, TypesEnum.poison],
      height: '0.9 m',
      weight: '45.5 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.poisonColor],
      img: './assets/images/Tentacool.png',
      icon: './assets/icons/Tentacool.png',
      audio: './assets/audio/Tentacool.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 73,
      name: 'Tentacruel',
      types: [TypesEnum.water, TypesEnum.poison],
      height: '1.6 m',
      weight: '55.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.poisonColor],
      img: './assets/images/Tentacruel.png',
      icon: './assets/icons/Tentacruel.png',
      audio: './assets/audio/Tentacruel.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 74,
      name: 'Geodude',
      evolutionLevel: 25,
      types: [TypesEnum.rock, TypesEnum.ground],
      height: '0.4 m',
      weight: '20.0 kg',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.groundColor],
      img: './assets/images/Geodude.png',
      icon: './assets/icons/Geodude.png',
      audio: './assets/audio/Geodude.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 75,
      name: 'Graveler',
      exchange: true,
      types: [TypesEnum.rock, TypesEnum.ground],
      height: '1.0 m',
      weight: '105.0 kg',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.groundColor],
      img: './assets/images/Graveler.png',
      icon: './assets/icons/Graveler.png',
      audio: './assets/audio/Graveler.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 76,
      name: 'Golem',
      types: [TypesEnum.rock, TypesEnum.ground],
      height: '1.4 m',
      weight: '300.0 kg',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.groundColor],
      img: './assets/images/Golem.png',
      icon: './assets/icons/Golem.png',
      audio: './assets/audio/Golem.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 77,
      name: 'Ponyta',
      evolutionLevel: 40,
      types: [TypesEnum.fire],
      height: '1.0 m',
      weight: '30.0 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Ponyta.png',
      icon: './assets/icons/Ponyta.png',
      audio: './assets/audio/Ponyta.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 78,
      name: 'Rapidash',
      types: [TypesEnum.fire],
      height: '1.7 m',
      weight: '95.0 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Rapidash.png',
      icon: './assets/icons/Rapidash.png',
      audio: './assets/audio/Rapidash.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 79,
      name: 'Slowpoke',
      evolutionLevel: 37,
      types: [TypesEnum.water, TypesEnum.psychic],
      height: '1.2 m',
      weight: '36.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.psychicColor],
      img: './assets/images/Slowpoke.png',
      icon: './assets/icons/Slowpoke.png',
      audio: './assets/audio/Slowpoke.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 80,
      name: 'Slowbro',
      types: [TypesEnum.water, TypesEnum.psychic],
      height: '1.6 m',
      weight: '78.5 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.psychicColor],
      img: './assets/images/Slowbro.png',
      icon: './assets/icons/Slowbro.png',
      audio: './assets/audio/Slowbro.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 81,
      name: 'Magnemite',
      evolutionLevel: 30,
      types: [TypesEnum.electric, TypesEnum.steel],
      height: '0.3 m',
      weight: '6.0 kg ',
      taux: 125,
      color: [ColorEnum.electricColor, ColorEnum.steelColor],
      img: './assets/images/Magnemite.png',
      icon: './assets/icons/Magnemite.png',
      audio: './assets/audio/Magnemite.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 82,
      name: 'Magneton',
      types: [TypesEnum.electric, TypesEnum.steel],
      height: '1.0 m',
      weight: '60.0 kg ',
      taux: 125,
      color: [ColorEnum.electricColor, ColorEnum.steelColor],
      img: './assets/images/Magneton.png',
      icon: './assets/icons/Magneton.png',
      audio: './assets/audio/Magneton.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 83,
      name: "Farfetch’d",
      types: [TypesEnum.normal, TypesEnum.flying],
      height: '0.8 m',
      weight: '15.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.flyingColor],
      img: "./assets/images/Farfetch’d.png",
      icon: './assets/icons/Farfetch’d.png',
      audio: "./assets/audio/Farfetch’d.ogg",
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 84,
      name: 'Doduo',
      evolutionLevel: 31,
      types: [TypesEnum.normal, TypesEnum.flying],
      height: '1.4 m',
      weight: '39.2 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.flyingColor],
      img: './assets/images/Doduo.png',
      icon: './assets/icons/Doduo.png',
      audio: './assets/audio/Doduov.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 85,
      name: 'Dodrio',
      types: [TypesEnum.normal, TypesEnum.flying],
      height: '1.8 m',
      weight: '85.2 kg',
      taux: 125,
      color: [ColorEnum.normalColor, ColorEnum.flyingColor],
      img: './assets/images/Dodrio.png',
      icon: './assets/icons/Dodrio.png',
      audio: './assets/audio/Dodrio.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 86,
      name: 'Seel',
      evolutionLevel: 34,
      types: [TypesEnum.water],
      height: '1.1 m',
      weight: '90.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Seel.png',
      icon: './assets/icons/Seel.png',
      audio: './assets/audio/Seel.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 87,
      name: 'Dewgong',
      types: [TypesEnum.water, TypesEnum.ice],
      height: '1.7 m',
      weight: '120.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.iceColor],
      img: './assets/images/Dewgong.png',
      icon: './assets/icons/Dewgong.png',
      audio: './assets/audio/Dewgong.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 88,
      name: 'Grimer',
      evolutionLevel: 38,
      types: [TypesEnum.poison],
      height: '0.9 m',
      weight: '30.0 kg ',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Grimer.png',
      icon: './assets/icons/Grimer.png',
      audio: './assets/audio/Grimer.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 89,
      name: 'Muk',
      types: [TypesEnum.poison],
      height: '1.2 m',
      weight: '30.0 kg ',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Muk.png',
      icon: './assets/icons/Muk.png',
      audio: './assets/audio/Muk.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 90,
      name: 'Shellder',
      stone: [StoneEnum.water],
      types: [TypesEnum.water],
      height: '0.3 m',
      weight: '4.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Shellder.png',
      icon: './assets/icons/Shellder.png',
      audio: './assets/audio/Shellder.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 91,
      name: 'Cloyster',
      types: [TypesEnum.water, TypesEnum.ice],
      height: '1.5 m',
      weight: '132.5 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.iceColor],
      img: './assets/images/Cloyster.png',
      icon: './assets/icons/Cloyster.png',
      audio: './assets/audio/Cloyster.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 92,
      name: 'Gastly',
      evolutionLevel: 25,
      types: [TypesEnum.ghost, TypesEnum.poison],
      height: '1.3 m',
      weight: '0.1 kg',
      taux: 125,
      color: [ColorEnum.ghostColor, ColorEnum.poisonColor],
      img: './assets/images/Gastly.png',
      icon: './assets/icons/Gastly.png',
      audio: './assets/audio/Gastly.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 93,
      name: 'Haunter',
      exchange: true,
      types: [TypesEnum.ghost, TypesEnum.poison],
      height: '1.6 m',
      weight: '0.1 kg',
      taux: 125,
      color: [ColorEnum.ghostColor, ColorEnum.poisonColor],
      img: './assets/images/Haunter.png',
      icon: './assets/icons/Haunter.png',
      audio: './assets/audio/Haunter.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 94,
      name: 'Gengar',
      types: [TypesEnum.ghost, TypesEnum.poison],
      height: '1.5 m',
      weight: '40.5 kg',
      taux: 125,
      color: [ColorEnum.ghostColor, ColorEnum.poisonColor],
      img: './assets/images/Gengar.png',
      icon: './assets/icons/Gengar.png',
      audio: './assets/audio/Gengar.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 95,
      name: 'Onix',
      types: [TypesEnum.rock],
      height: '8.8 m',
      weight: '210.0 kg ',
      taux: 125,
      color: [ColorEnum.rockColor],
      img: './assets/images/Onix.png',
      icon: './assets/icons/Onix.png',
      audio: './assets/audio/Onix.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 96,
      name: 'Drowzee',
      evolutionLevel: 26,
      types: [TypesEnum.psychic],
      height: '1.0 m',
      weight: '32.4 kg ',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Drowzee.png',
      icon: './assets/icons/Drowzee.png',
      audio: './assets/audio/Drowzee.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 97,
      name: 'Hypno',
      types: [TypesEnum.psychic],
      height: '1.6 m',
      weight: '75.6 kg',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Hypno.png',
      icon: './assets/icons/Hypno.png',
      audio: './assets/audio/Hypno.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 98,
      name: 'Krabby',
      evolutionLevel: 28,
      types: [TypesEnum.water],
      height: '0.4 m',
      weight: '6.5 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Krabby.png',
      icon: './assets/icons/Krabby.png',
      audio: './assets/audio/Krabby.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 99,
      name: 'Kingler',
      types: [TypesEnum.water],
      height: '1.3 m',
      weight: '60.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Kingler.png',
      icon: './assets/icons/Kingler.png',
      audio: './assets/audio/Kingler.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 100,
      name: 'Voltorb',
      evolutionLevel: 30,
      types: [TypesEnum.electric],
      height: '0.5 m',
      weight: '10.4 kg',
      taux: 125,
      color: [ColorEnum.electricColor],
      img: './assets/images/Voltorb.png',
      icon: './assets/icons/Voltorb.png',
      audio: './assets/audio/Voltorb.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 101,
      name: 'Electrode',
      types: [TypesEnum.electric],
      height: '1.2 m',
      weight: '66.6 kg',
      taux: 125,
      color: [ColorEnum.electricColor],
      img: './assets/images/Electrode.png',
      icon: './assets/icons/Electrode.png',
      audio: './assets/audio/Electrode.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 102,
      name: 'Exeggcute',
      stone: [StoneEnum.leaf],
      types: [TypesEnum.grass, TypesEnum.psychic],
      height: '0.4 m',
      weight: '2.5 kg ',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.psychicColor],
      img: './assets/images/Exeggcute.png',
      icon: './assets/icons/Exeggcute.png',
      audio: './assets/audio/Exeggcute.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 103,
      name: 'Exeggutor',
      types: [TypesEnum.grass, TypesEnum.psychic],
      height: '2.0 m',
      weight: '120.0 kg ',
      taux: 125,
      color: [ColorEnum.grassColor, ColorEnum.psychicColor],
      img: './assets/images/Exeggutor.png',
      icon: './assets/icons/Exeggutor.png',
      audio: './assets/audio/Exeggutor.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 104,
      name: 'Cubone',
      evolutionLevel: 28,
      types: [TypesEnum.ground],
      height: '0.4 m',
      weight: '6.5 kg',
      taux: 125,
      color: [ColorEnum.groundColor],
      img: './assets/images/Cubone.png',
      icon: './assets/icons/Cubone.png',
      audio: './assets/audio/Cubone.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 105,
      name: 'Marowak',
      types: [TypesEnum.ground],
      height: '1.0 m',
      weight: '45.0 kg',
      taux: 125,
      color: [ColorEnum.groundColor],
      img: './assets/images/Marowak.png',
      icon: './assets/icons/Marowak.png',
      audio: './assets/audio/Marowak.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 106,
      name: 'Hitmonlee',
      types: [TypesEnum.fighting],
      height: '1.5 m',
      weight: '49.8 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Hitmonlee.png',
      icon: './assets/icons/Hitmonlee.png',
      audio: './assets/audio/Hitmonlee.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 107,
      name: 'Hitmonchan',
      types: [TypesEnum.fighting],
      height: '1.4 m',
      weight: '50.2 kg',
      taux: 125,
      color: [ColorEnum.fightingColor],
      img: './assets/images/Hitmonchan.png',
      icon: './assets/icons/Hitmonchan.png',
      audio: './assets/audio/Hitmonchan.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 108,
      name: 'Lickitung',
      types: [TypesEnum.normal],
      height: '1.2 m',
      weight: '65.5 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Lickitung.png',
      icon: './assets/icons/Lickitung.png',
      audio: './assets/audio/Lickitung.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 109,
      name: 'Koffing',
      evolutionLevel: 35,
      types: [TypesEnum.poison],
      height: '0.6 m',
      weight: '1.0 kg ',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Koffing.png',
      icon: './assets/icons/Koffing.png',
      audio: './assets/audio/Koffing.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 110,
      name: 'Weezing',
      types: [TypesEnum.poison],
      height: '1.2 m',
      weight: '9.5 kg ',
      taux: 125,
      color: [ColorEnum.poisonColor],
      img: './assets/images/Weezing.png',
      icon: './assets/icons/Weezing.png',
      audio: './assets/audio/Weezing.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 111,
      name: 'Rhyhorn',
      evolutionLevel: 42,
      types: [TypesEnum.ground, TypesEnum.rock],
      height: '1.0 m',
      weight: '115.0 kg',
      taux: 125,
      color: [ColorEnum.groundColor, ColorEnum.rockColor],
      img: './assets/images/Rhyhorn.png',
      icon: './assets/icons/Rhyhorn.png',
      audio: './assets/audio/Rhyhorn.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 112,
      name: 'Rhydon',
      types: [TypesEnum.ground, TypesEnum.rock],
      height: '1.9 m',
      weight: '120.0 kg',
      taux: 125,
      color: [ColorEnum.groundColor, ColorEnum.rockColor],
      img: './assets/images/Rhydon.png',
      icon: './assets/icons/Rhydon.png',
      audio: './assets/audio/Rhydon.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 113,
      name: 'Chansey',
      types: [TypesEnum.normal],
      height: '1.1 m',
      weight: '34.6 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Chansey.png',
      icon: './assets/icons/Chansey.png',
      audio: './assets/audio/Chansey.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 114,
      name: 'Tangela',
      types: [TypesEnum.grass],
      height: '1.0 m',
      weight: '35.0 kg',
      taux: 125,
      color: [ColorEnum.grassColor],
      img: './assets/images/Tangela.png',
      icon: './assets/icons/Tangela.png',
      audio: './assets/audio/Tangela.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 115,
      name: 'Kangaskhan',
      types: [TypesEnum.normal],
      height: '2.2 m',
      weight: '80.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Kangaskhan.png',
      icon: './assets/icons/Kangaskhan.png',
      audio: './assets/audio/Kangaskhan.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 116,
      name: 'Horsea',
      evolutionLevel: 32,
      types: [TypesEnum.water],
      height: '0.4 m',
      weight: '8.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Horsea.png',
      icon: './assets/icons/Horsea.png',
      audio: './assets/audio/Horsea.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 117,
      name: 'Seadra',
      evolutionLevel: 33,
      types: [TypesEnum.water],
      height: '0.6 m',
      weight: '15.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Seadra.png',
      icon: './assets/icons/Seadra.png',
      audio: './assets/audio/Seadra.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 118,
      name: 'Goldeen',
      evolutionLevel: 33,
      types: [TypesEnum.water],
      height: '0.6 m',
      weight: '15.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Goldeen.png',
      icon: './assets/icons/Goldeen.png',
      audio: './assets/audio/Goldeen.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 119,
      name: 'Seaking',
      types: [TypesEnum.water],
      height: '1.3 m',
      weight: '39.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Seaking.png',
      icon: './assets/icons/Seaking.png',
      audio: './assets/audio/Seaking.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 120,
      name: 'Staryu',
      stone: [StoneEnum.water],
      types: [TypesEnum.water],
      height: '0.8 m',
      weight: '34.5 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Staryu.png',
      icon: './assets/icons/Staryu.png',
      audio: './assets/audio/Staryu.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 15625
    },
    {
      id: 121,
      name: 'Starmie',
      types: [TypesEnum.water, TypesEnum.psychic],
      height: '1.1 m',
      weight: '80.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.psychicColor],
      img: './assets/images/Starmie.png',
      icon: './assets/icons/Starmie.png',
      audio: './assets/audio/Starmie.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 122,
      name: 'Mr. Mime',
      types: [TypesEnum.psychic, TypesEnum.fairy],
      height: '1.3 m',
      weight: '54.5 kg',
      taux: 125,
      color: [ColorEnum.psychicColor, ColorEnum.fairyColor],
      img: './assets/images/MrMime.png',
      icon: './assets/icons/MrMime.png',
      audio: './assets/audio/MrMime.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 123,
      name: 'Scyther',
      types: [TypesEnum.bug, TypesEnum.flying],
      height: '1.5 m',
      weight: '56.0 kg',
      taux: 125,
      color: [ColorEnum.bugColor, ColorEnum.flyingColor],
      img: './assets/images/Scyther.png',
      icon: './assets/icons/Scyther.png',
      audio: './assets/audio/Scyther.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 124,
      name: 'Jynx',
      types: [TypesEnum.ice, TypesEnum.psychic],
      height: '1.4 m',
      weight: '40.6 kg',
      taux: 125,
      color: [ColorEnum.iceColor, ColorEnum.psychicColor],
      img: './assets/images/Jynx.png',
      icon: './assets/icons/Jynx.png',
      audio: './assets/audio/Jynx.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 125,
      name: 'Electabuzz',
      types: [TypesEnum.electric],
      height: '1.1 m',
      weight: '30.0 kg',
      taux: 125,
      color: [ColorEnum.electricColor],
      img: './assets/images/Electabuzz.png',
      icon: './assets/icons/Electabuzz.png',
      audio: './assets/audio/Electabuzz.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 126,
      name: 'Magmar',
      types: [TypesEnum.fire],
      height: '1.3 m',
      weight: '44.5 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Magmar.png',
      icon: './assets/icons/Magmar.png',
      audio: './assets/audio/Magmar.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 127,
      name: 'Pinsir',
      types: [TypesEnum.bug],
      height: '1.5 m',
      weight: '55.0 kg',
      taux: 125,
      color: [ColorEnum.bugColor],
      img: './assets/images/Pinsir.png',
      icon: './assets/icons/Pinsir.png',
      audio: './assets/audio/Pinsir.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 128,
      name: 'Tauros',
      types: [TypesEnum.normal],
      height: '1.4 m',
      weight: '88.4 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Tauros.png',
      icon: './assets/icons/Tauros.png',
      audio: './assets/audio/Tauros.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 129,
      name: 'Magikarp',
      evolutionLevel: 20,
      types: [TypesEnum.water],
      height: '0.9 m',
      weight: '10.0 kg ',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Magikarp.png',
      icon: './assets/icons/Magikarp.png',
      audio: './assets/audio/Magikarp.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 109011.25
    },
    {
      id: 130,
      name: 'Gyarados',
      types: [TypesEnum.water, TypesEnum.flying],
      height: '6.5 m',
      weight: '235.0 kg ',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.flyingColor],
      img: './assets/images/Gyarados.png',
      icon: './assets/icons/Gyarados.png',
      audio: './assets/audio/Gyarados.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 131,
      name: 'Lapras',
      types: [TypesEnum.water, TypesEnum.ice],
      height: '2.5 m',
      weight: '220.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor, ColorEnum.iceColor],
      img: './assets/images/Lapras.png',
      icon: './assets/icons/Lapras.png',
      audio: './assets/audio/Lapras.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 132,
      name: 'Ditto',
      types: [TypesEnum.normal],
      height: '0.3 m',
      weight: '4.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Ditto.png',
      icon: './assets/icons/Ditto.png',
      audio: './assets/audio/Ditto.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 133,
      name: 'Eevee',
      stone: [StoneEnum.water, StoneEnum.thunder, StoneEnum.fire],
      types: [TypesEnum.normal],
      height: '0.3 m',
      weight: '6.5 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Eevee.png',
      icon: './assets/icons/Eevee.png',
      audio: './assets/audio/Eevee.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 134,
      name: 'Vaporeon',
      types: [TypesEnum.water],
      height: '1.0 m',
      weight: '29.0 kg',
      taux: 125,
      color: [ColorEnum.waterColor],
      img: './assets/images/Vaporeon.png',
      icon: './assets/icons/Vaporeon.png',
      audio: './assets/audio/Vaporeon.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 135,
      name: 'Jolteon',
      types: [TypesEnum.electric],
      height: '0.8 m',
      weight: '24.5 kg',
      taux: 125,
      color: [ColorEnum.electricColor],
      img: './assets/images/Jolteon.png',
      icon: './assets/icons/Jolteon.png',
      audio: './assets/audio/Jolteon.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 136,
      name: 'Flareon',
      types: [TypesEnum.fire],
      height: '0.9 m',
      weight: '25.0 kg',
      taux: 125,
      color: [ColorEnum.fireColor],
      img: './assets/images/Flareon.png',
      icon: './assets/icons/Flareon.png',
      audio: './assets/audio/Flareon.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 137,
      name: 'Porygon',
      types: [TypesEnum.normal],
      height: '0.8 m',
      weight: '36.5 kg ',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Porygon.png',
      icon: './assets/icons/Porygon.png',
      audio: './assets/audio/Porygon.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 138,
      name: 'Omanyte',
      evolutionLevel: 40,
      types: [TypesEnum.rock, TypesEnum.water],
      height: '0.4 m',
      weight: '7.5 kg ',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.waterColor],
      img: './assets/images/Omanyte.png',
      icon: './assets/icons/Omanyte.png',
      audio: './assets/audio/Omanyte.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 139,
      name: 'Omastar',
      types: [TypesEnum.rock, TypesEnum.water],
      height: '1.0 m',
      weight: '35.0 kg ',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.waterColor],
      img: './assets/images/Omastar.png',
      icon: './assets/icons/Omastar.png',
      audio: './assets/audio/Omastar.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 140,
      name: 'Kabuto',
      types: [TypesEnum.rock, TypesEnum.water],
      height: '0.5 m',
      weight: '11.5 kg ',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.waterColor],
      img: './assets/images/Kabuto.png',
      icon: './assets/icons/Kabuto.png',
      audio: './assets/audio/Kabuto.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 141,
      name: 'Kabutops',
      types: [TypesEnum.rock, TypesEnum.water],
      height: '1.3 m',
      weight: '40.5 kg ',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.waterColor],
      img: './assets/images/Kabutops.png',
      icon: './assets/icons/Kabutops.png',
      audio: './assets/audio/Kabutops.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 142,
      name: 'Aerodactyl',
      types: [TypesEnum.rock, TypesEnum.flying],
      height: '1.8 m',
      weight: '59.0 kg ',
      taux: 125,
      color: [ColorEnum.rockColor, ColorEnum.flyingColor],
      img: './assets/images/Aerodactyl.png',
      icon: './assets/icons/Aerodactyl.png',
      audio: './assets/audio/Aerodactyl.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 143,
      name: 'Snorlax',
      types: [TypesEnum.normal],
      height: '2.1 m',
      weight: '460.0 kg',
      taux: 125,
      color: [ColorEnum.normalColor],
      img: './assets/images/Snorlax.png',
      icon: './assets/icons/Snorlax.png',
      audio: './assets/audio/Snorlax.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 144,
      name: 'Articuno',
      types: [TypesEnum.ice, TypesEnum.flying],
      height: '1.7 m',
      weight: '55.4 kg ',
      taux: 125,
      color: [ColorEnum.iceColor, ColorEnum.flyingColor],
      img: './assets/images/Articuno.png',
      icon: './assets/icons/Articuno.png',
      audio: './assets/audio/Articuno.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: true,
      generation: '1',
      encounterRate: 1
    },
    {
      id: 145,
      name: 'Zapdos',
      types: [TypesEnum.electric, TypesEnum.flying],
      height: '1.6 m',
      weight: '52.6 kg ',
      taux: 125,
      color: [ColorEnum.electricColor, ColorEnum.flyingColor],
      img: './assets/images/Zapdos.png',
      icon: './assets/icons/Zapdos.png',
      audio: './assets/audio/Zapdos.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw'],
      isLegendary: true,
      generation: '1',
      encounterRate: 1
    },
    {
      id: 146,
      name: 'Moltres',
      types: [TypesEnum.fire, TypesEnum.flying],
      height: '2.0 m',
      weight: '60.0 kg',
      taux: 125,
      color: [ColorEnum.fireColor, ColorEnum.flyingColor],
      img: './assets/images/Moltres.png',
      icon: './assets/icons/Moltres.png',
      audio: './assets/audio/Moltres.ogg',
      attacks: ['Tackle', 'String Shot'],
      isLegendary: true,
      generation: '1',
      encounterRate: 1
    },
    {
      id: 147,
      name: 'Dratini',
      evolutionLevel: 30,
      types: [TypesEnum.dragon],
      height: '1.8 m',
      weight: '3.3 kg',
      taux: 125,
      color: [ColorEnum.dragonColor],
      img: './assets/images/Dratini.png',
      icon: './assets/icons/Dratini.png',
      audio: './assets/audio/Dratini.ogg',
      attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind'],
      isLegendary: false,
      generation: '1',
      encounterRate: 2083.33
    },
    {
      id: 148,
      name: 'Dragonair',
      evolutionLevel: 55,
      types: [TypesEnum.dragon],
      height: '1.1 m',
      weight: '30.0 kg',
      taux: 125,
      color: [ColorEnum.dragonColor],
      img: './assets/images/Dragonair.png',
      icon: './assets/icons/Dragonair.png',
      audio: './assets/audio/Dragonair.ogg',
      attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip'],
      isLegendary: false,
      generation: '1',
      encounterRate: 208.33
    },
    {
      id: 149,
      name: 'Dragonite',
      types: [TypesEnum.dragon, TypesEnum.flying],
      height: '2.2 m',
      weight: '210 kg',
      taux: 125,
      color: [ColorEnum.dragonColor, ColorEnum.flyingColor],
      img: './assets/images/Dragonite.png',
      icon: './assets/icons/Dragonite.png',
      audio: './assets/audio/Dragonite.ogg',
      attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave'],
      isLegendary: false,
      generation: '1',
      encounterRate: 25
    },
    {
      id: 150,
      name: 'Mewtwo',
      types: [TypesEnum.psychic],
      height: '2.0 m',
      weight: '122 kg',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Mewtwo.png',
      icon: './assets/icons/Mewtwo.png',
      audio: './assets/audio/Mewtwo.ogg',
      attacks: ['Scratch', 'Growl', 'Ember', 'Leer'],
      isLegendary: true,
      generation: '1',
      encounterRate: 1
    },
    {
      id: 151,
      name: 'Mew',
      types: [TypesEnum.psychic],
      height: '0.4 m',
      weight: '4.0 kg ',
      taux: 125,
      color: [ColorEnum.psychicColor],
      img: './assets/images/Mew.png',
      icon: './assets/icons/Mew.png',
      audio: './assets/audio/Mew.ogg',
      attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun'],
      isLegendary: true,
      generation: '1',
      encounterRate: 0.1
    },
  ];

  constructor(readonly http: HttpClient) {
  }

  getDetailsPokemon(id: number): Pokemon {
    return this.pokemonArray[id - 1];
  }

  getAllPokemons(): Array<Pokemon> {
    return this.pokemonArray;
  }
}
