import {Injectable} from '@angular/core';
import {Pokemon} from '../interfaces/pokemon';
import {Types} from '../enums/types.enum';
import {HttpClient} from '@angular/common/http';
import {Color} from '../enums/color.enum';

@Injectable({
  providedIn: 'root'
})
export class AllPokemonsService {

  pokemonArray: Array<Pokemon>;

  constructor(readonly http: HttpClient) {
    this.pokemonArray = [
      {
        id: 1,
        name: 'Bulbasaur',
        evolutionLevel: 16,
        types: [Types.grass],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.grassColor],
        img: '../../assets/images/Bulbasaur.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 2,
        name: 'Ivysaur',
        evolutionLevel: 32,
        types: [Types.grass],
        height: '1.0 m',
        weight: '13 kg',
        color: [Color.grassColor],
        img: '../../assets/images/Ivysaur.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'The bulb on its back grows by drawing energy. It gives off an aroma when it is ready to bloom. ',
        attacks: [' Vine Whip', 'Razor Leaf', ' Seed Bomb', 'Solar Beam']
      },
      {
        id: 3,
        name: 'Venusaur',
        types: [Types.grass],
        height: '2.4 m',
        weight: '155.5 kg',
        color: [Color.grassColor],
        img: '../../assets/images/Venusaur.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flower on its back catches the sun\'s rays. The sunlight is then absorbed and used for energy. ',
        attacks: [' Vine Whip', 'Razor Leaf', ' Seed Bomb', 'Solar Beam']
      },
      {
        id: 4,
        name: 'Charmander',
        evolutionLevel: 16,
        types: [Types.fire],
        height: '0.6 m',
        weight: '8.5 kg',
        color: [Color.fireColor],
        img: '../../assets/images/Charmander.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 5,
        name: 'Charmeleon',
        evolutionLevel: 32,
        types: [Types.fire],
        height: '1.1 m',
        weight: '19.0kg',
        color: [Color.fireColor],
        img: '../../assets/images/Charmeleon.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Tough fights could excite this Pokémon. When excited, it may blow out bluish-white flames. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 6,
        name: 'Charizard',
        types: [Types.fire],
        height: '1.7 m',
        weight: '90.5kg',
        color: [Color.fireColor],
        img: '../../assets/images/Charizard.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'When expelling a blast of super hot fire, the red flame at the tip of its tail burns more intensely. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 7,
        name: 'Squirtle',
        evolutionLevel: 16,
        types: [Types.water],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.waterColor],
        img: '../../assets/images/Squirtle.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 8,
        name: 'Wartortle',
        evolutionLevel: 32,
        types: [Types.water],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.waterColor],
        img: '../../assets/images/Wartortle.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 9,
        name: 'Blastoise',
        types: [Types.water],
        height: '1.6m',
        weight: '85.5 kg',
        color: [Color.waterColor],
        img: '../../assets/images/Blastoise.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Once it takes aim at its enemy, it blasts out water with even more force than a fire hose. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 10,
        name: 'Caterpie',
        types: [Types.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 11,
        name: 'Metapod',
        types: [Types.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 12,
        name: 'Butterfree',
        types: [Types.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 13,
        name: 'Weedle',
        types: [Types.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 14,
        name: 'Kakuna',
        types: [Types.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 15,
        name: 'Beedrill',
        types: [Types.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 16,
        name: 'Pidgey',
        types: [Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 17,
        name: 'Pidgeotto',
        types: [Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 18,
        name: 'Pidgeot',
        types: [Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 19,
        name: 'Rattata',
        types: [Types.normal],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 20,
        name: 'Raticate',
        types: [Types.normal],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 21,
        name: 'Spearow',
        types: [Types.normal, Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.normalColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 22,
        name: 'Fearow',
        types: [Types.normal, Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.normalColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 23,
        name: 'Ekans',
        types: [Types.poison],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 24,
        name: 'Arbok',
        types: [Types.poison],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 25,
        name: 'Pikachu',
        types: [Types.electric],
        height: '0.4m',
        weight: '6kg',
        color: [Color.electricColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 26,
        name: 'Raichu',
        types: [Types.electric],
        height: '0.4m',
        weight: '6kg',
        color: [Color.electricColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 27,
        name: 'Sandshrew',
        evolutionLevel: 16,
        types: [Types.ground],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 28,
        name: 'Sandslash',
        types: [Types.ground],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.groundColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 29,
        name: 'Nidoran♀',
        types: [Types.poison],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 30,
        name: 'Nidorina',
        types: [Types.poison],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 31,
        name: 'Nidoqueen',
        types: [Types.poison, Types.ground],
        height: '0.4m',
        weight: '6kg',
        color: [Color.poisonColor, Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 32,
        name: 'Nidoran♂',
        types: [Types.poison],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 33,
        name: 'Nidorino',
        types: [Types.poison],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 34,
        name: 'Nidoking',
        types: [Types.poison, Types.poison],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.poisonColor, Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 35,
        name: 'Clefairy',
        evolutionLevel: 16,
        types: [Types.fairy],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.fairyColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 36,
        name: 'Clefable',
        types: [Types.fairy],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.fairyColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 37,
        name: 'Vulpix',
        types: [Types.fire],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 38,
        name: 'Ninetales',
        types: [Types.fire],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 39,
        name: 'Jigglypuff',
        types: [Types.normal, Types.fairy],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.normalColor, Color.fairyColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 40,
        name: 'Zubat',
        types: [Types.poison, Types.flying],
        height: '0.4m',
        weight: '6kg',
        color: [Color.poisonColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 41,
        name: 'Golbat',
        types: [Types.poison, Types.flying],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.poisonColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 43,
        name: 'Oddish',
        evolutionLevel: 16,
        types: [Types.grass, Types.poison],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.grassColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 44,
        name: 'Gloom',
        types: [Types.grass, Types.poison],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.grassColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 45,
        name: 'Vileplume',
        types: [Types.grass, Types.poison],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.grassColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 46,
        name: 'Paras',
        types: [Types.bug, Types.grass],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.bugColor, Color.grassColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 47,
        name: 'Parasect',
        types: [Types.bug, Types.grass],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.bugColor, Color.grassColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 48,
        name: 'Venonat',
        types: [Types.bug, Types.poison],
        height: '0.4m',
        weight: '6kg',
        color: [Color.bugColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 49,
        name: 'Venomoth',
        types: [Types.bug, Types.poison],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.bugColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 50,
        name: 'Diglett',
        evolutionLevel: 16,
        types: [Types.ground],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 51,
        name: 'Dugtrio',
        types: [Types.ground],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.groundColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 52,
        name: 'Meowth',
        types: [Types.normal],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 53,
        name: 'Persian',
        types: [Types.normal],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 55,
        name: 'Psyduck',
        types: [Types.water],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 56,
        name: 'Golduck',
        types: [Types.water],
        height: '0.4m',
        weight: '6kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 57,
        name: 'Mankey',
        types: [Types.fighting],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 58,
        name: 'Growlithe',
        types: [Types.fire],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 59,
        name: 'Arcanine',
        types: [Types.fire],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 60,
        name: 'Poliwag',
        types: [Types.water],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 61,
        name: 'Poliwhirl',
        evolutionLevel: 16,
        types: [Types.water],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 62,
        name: 'Poliwrath',
        types: [Types.water, Types.fighting],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.waterColor, Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 63,
        name: 'Abra',
        types: [Types.psychic],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 64,
        name: 'Kadabra',
        types: [Types.psychic],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 65,
        name: 'Alakazam',
        types: [Types.psychic],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 66,
        name: 'Machop',
        types: [Types.fighting],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 67,
        name: 'Machoke',
        types: [Types.fighting],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 68,
        name: 'Machamp',
        types: [Types.fighting],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 69,
        name: 'Bellsprout',
        types: [Types.grass, Types.poison],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.grassColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 70,
        name: 'Weepinbell',
        types: [Types.grass, Types.poison],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.grassColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 71,
        name: 'Victreebel',
        types: [Types.grass, Types.poison],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.grassColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 72,
        name: 'Tentacool',
        types: [Types.water, Types.poison],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.waterColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 73,
        name: 'Tentacruel',
        types: [Types.water, Types.poison],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.waterColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 74,
        name: 'Geodude',
        types: [Types.rock, Types.ground],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.rockColor, Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 75,
        name: 'Graveler',
        types: [Types.rock, Types.ground],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.rockColor, Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 76,
        name: 'Golem',
        types: [Types.rock, Types.ground],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.rockColor, Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 77,
        name: 'Ponyta',
        types: [Types.fire],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 78,
        name: 'Rapidash',
        types: [Types.fire],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 79,
        name: 'Slowpoke',
        types: [Types.water, Types.psychic],
        height: '0.4m',
        weight: '6kg',
        color: [Color.waterColor, Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 80,
        name: 'Slowbro',
        types: [Types.water, Types.psychic],
        height: '0.4m',
        weight: '6kg',
        color: [Color.waterColor, Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 81,
        name: 'Magnemite',
        evolutionLevel: 16,
        types: [Types.electric, Types.steel],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.electricColor, Color.steelColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 82,
        name: 'Magneton',
        types: [Types.electric, Types.steel],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.electricColor, Color.steelColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 83,
        name: 'Farfetch\'d',
        types: [Types.normal, Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.normalColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 84,
        name: 'Doduo',
        types: [Types.normal, Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.normalColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 85,
        name: 'Dodrio',
        types: [Types.normal, Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.normalColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 86,
        name: 'Seel',
        types: [Types.water],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 87,
        name: 'Dewgong',
        types: [Types.water, Types.ice],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.waterColor, Color.iceColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 88,
        name: 'Grimer',
        evolutionLevel: 16,
        types: [Types.poison],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 89,
        name: 'Muk',
        types: [Types.poison],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 90,
        name: 'Shellder',
        types: [Types.water],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 91,
        name: 'Cloyster',
        types: [Types.water, Types.ice],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.waterColor, Color.iceColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 92,
        name: 'Gastly',
        types: [Types.ghost, Types.poison],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.ghostColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 93,
        name: 'Haunter',
        types: [Types.ghost, Types.poison],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.ghostColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 94,
        name: 'Gengar',
        types: [Types.ghost, Types.poison],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.ghostColor, Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 95,
        name: 'Onix',
        types: [Types.rock],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.rockColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 96,
        name: 'Drowzee',
        types: [Types.psychic],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 97,
        name: 'Hypno',
        types: [Types.psychic],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 98,
        name: 'Krabby',
        types: [Types.water],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 99,
        name: 'Kingler',
        types: [Types.water],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 100,
        name: 'Voltorb',
        types: [Types.electric],
        height: '0.4m',
        weight: '6kg',
        color: [Color.electricColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 101,
        name: 'Electrode',
        types: [Types.electric],
        height: '0.4m',
        weight: '6kg',
        color: [Color.electricColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 102,
        name: 'Exeggcute',
        evolutionLevel: 16,
        types: [Types.grass, Types.psychic],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.grassColor, Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 103,
        name: 'Exeggutor',
        types: [Types.grass, Types.psychic],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.grassColor, Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 104,
        name: 'Cubone',
        types: [Types.ground],
        height: '0.4m',
        weight: '6kg',
        color: [Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 105,
        name: 'Marowak',
        types: [Types.ground],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.groundColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 106,
        name: 'Hitmonlee',
        types: [Types.fighting],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 107,
        name: 'Hitmonchan',
        types: [Types.fighting],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.fightingColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 108,
        name: 'Lickitung',
        types: [Types.normal],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 109,
        name: 'Koffing',
        evolutionLevel: 16,
        types: [Types.poison],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 110,
        name: 'Weezing',
        types: [Types.poison],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.poisonColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 111,
        name: 'Rhyhorn',
        types: [Types.ground, Types.rock],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.groundColor, Color.rockColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 112,
        name: 'Rhydon',
        types: [Types.ground, Types.rock],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.groundColor, Color.rockColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 113,
        name: 'Chansey',
        types: [Types.normal],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 114,
        name: 'Tangela',
        types: [Types.grass],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.grassColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 115,
        name: 'Kangaskhan',
        types: [Types.normal],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 116,
        name: 'Horsea',
        types: [Types.water],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 117,
        name: 'Seadra',
        types: [Types.water],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 118,
        name: 'Goldeen',
        types: [Types.water],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 119,
        name: 'Seaking',
        types: [Types.water],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 120,
        name: 'Staryu',
        types: [Types.water],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 121,
        name: 'Starmie',
        types: [Types.water, Types.psychic],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.waterColor, Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 122,
        name: 'Mr. Mime',
        types: [Types.psychic, Types.fairy],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.psychicColor, Color.fairyColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 123,
        name: 'Scyther',
        types: [Types.bug, Types.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.bugColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 124,
        name: 'Jynx',
        types: [Types.ice, Types.psychic],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.iceColor, Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 125,
        name: 'Electabuzz',
        types: [Types.electric],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.electricColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 126,
        name: 'Magmar',
        types: [Types.fire],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 127,
        name: 'Pinsir',
        types: [Types.bug],
        height: '0.4m',
        weight: '6kg',
        color: [Color.bugColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 128,
        name: 'Tauros',
        types: [Types.normal],
        height: '0.4m',
        weight: '6kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 129,
        name: 'Magikarp',
        evolutionLevel: 16,
        types: [Types.water],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 130,
        name: 'Gyarados',
        types: [Types.water, Types.flying],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.waterColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 131,
        name: 'Lapras',
        types: [Types.water, Types.ice],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.waterColor, Color.iceColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 132,
        name: 'Ditto',
        types: [Types.normal],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 133,
        name: 'Eevee',
        types: [Types.normal],
        height: '0.4m',
        weight: '6kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 134,
        name: 'Vaporeon',
        types: [Types.water],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 135,
        name: 'Jolteon',
        types: [Types.electric],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.electricColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 136,
        name: 'Flareon',
        types: [Types.fire],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.fireColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 137,
        name: 'Porygon',
        evolutionLevel: 16,
        types: [Types.normal],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 138,
        name: 'Omanyte',
        types: [Types.rock, Types.water],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.rockColor, Color.waterColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 139,
        name: 'Omastar',
        types: [Types.rock, Types.water],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.rockColor, Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 140,
        name: 'Kabuto',
        types: [Types.rock, Types.water],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.rockColor, Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 141,
        name: 'Kabutops',
        types: [Types.rock, Types.water],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.rockColor, Color.waterColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 142,
        name: 'Zubat',
        types: [Types.rock, Types.flying],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.rockColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 143,
        name: 'Snorlax',
        types: [Types.normal],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.normalColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 144,
        name: 'Articuno',
        types: [Types.ice, Types.flying],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.iceColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 145,
        name: 'Zapdos',
        types: [Types.electric, Types.flying],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [Color.electricColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/2/2a/Carabaffe-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 146,
        name: 'Moltres',
        types: [Types.fire, Types.flying],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [Color.fireColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/c7/Chenipan-RFVF.png/375px-Chenipan-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 147,
        name: 'Dratini',
        types: [Types.dragon],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.dragonColor],
        img: 'https://www.pokepedia.fr/images/thumb/9/94/Roucool-RFVF.png/375px-Roucool-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. ' +
          'It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 148,
        name: 'Dragonair',
        types: [Types.dragon],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [Color.dragonColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/ef/Bulbizarre-RFVF.png/375px-Bulbizarre-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 149,
        name: 'Dragonite',
        types: [Types.dragon, Types.flying],
        height: '0.4m',
        weight: '6kg',
        color: [Color.dragonColor, Color.flyingColor],
        img: 'https://www.pokepedia.fr/images/thumb/e/e7/Pikachu-RFVF.png/375px-Pikachu-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. ' +
          'If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 150,
        name: 'Mewtwo',
        types: [Types.psychic],
        height: '0.6m',
        weight: '8.5kg',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/8/89/Salam%C3%A8che-RFVF.png/375px-Salam%C3%A8che-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 151,
        name: 'Mew',
        evolutionLevel: 16,
        types: [Types.psychic],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [Color.psychicColor],
        img: 'https://www.pokepedia.fr/images/thumb/c/cc/Carapuce-RFVF.png/375px-Carapuce-RFVF.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
    ];
  }

  getDetailsPokemon(id: number) {
    return this.pokemonArray[id - 1];
  }

  getAllPokemons(): Array<Pokemon> {
    return this.pokemonArray;
  }
}
