import {Injectable} from '@angular/core';
import {Pokemon} from '../interfaces/pokemon';
import {TypesEnum} from '../enums/types.enum';
import {HttpClient} from '@angular/common/http';
import {ColorEnum} from '../enums/color.enum';
import {Observable, of} from 'rxjs';
import {StoneEnum} from '../enums/stone.enum';

@Injectable({
  providedIn: 'root'
})
export class AllPokemonService {

  pokemonArray: Array<Pokemon>;

  constructor(readonly http: HttpClient) {
    this.pokemonArray = [
      {
        id: 1,
        name: 'Bulbasaur',
        evolutionLevel: 16,
        types: [TypesEnum.grass],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [ColorEnum.grassColor],
        img: '../../assets/images/Bulbasaur.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'It can go for days without eating a single morsel. In the bulb on its back, it stores energy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 2,
        name: 'Ivysaur',
        evolutionLevel: 32,
        types: [TypesEnum.grass],
        height: '1.0 m',
        weight: '13 kg',
        color: [ColorEnum.grassColor],
        img: '../../assets/images/Ivysaur.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'The bulb on its back grows by drawing energy. It gives off an aroma when it is ready to bloom. ',
        attacks: [' Vine Whip', 'Razor Leaf', ' Seed Bomb', 'Solar Beam']
      },
      {
        id: 3,
        name: 'Venusaur',
        types: [TypesEnum.grass],
        height: '2.0 m',
        weight: '100.0 kg',
        color: [ColorEnum.grassColor],
        img: '../../assets/images/Venusaur.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flower on its back catches the sun\'s rays. The sunlight is then absorbed and used for energy. ',
        attacks: [' Vine Whip', 'Razor Leaf', ' Seed Bomb', 'Solar Beam']
      },
      {
        id: 4,
        name: 'Charmander',
        evolutionLevel: 16,
        types: [TypesEnum.fire],
        height: '0.6 m',
        weight: '8.5 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Charmander.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 5,
        name: 'Charmeleon',
        evolutionLevel: 32,
        types: [TypesEnum.fire],
        height: '1.1 m',
        weight: '19.0 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Charmeleon.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Tough fights could excite this Pokémon. When excited, it may blow out bluish-white flames. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 6,
        name: 'Charizard',
        types: [TypesEnum.fire],
        height: '1.7 m',
        weight: '90.5 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Charizard.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'When expelling a blast of super hot fire, the red flame at the tip of its tail burns more intensely. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 7,
        name: 'Squirtle',
        evolutionLevel: 16,
        types: [TypesEnum.water],
        height: '0.5 m',
        weight: '9.0 kg ',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Squirtle.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Shoots water at prey while in the water. Withdraws into its shell when in danger. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 8,
        name: 'Wartortle',
        evolutionLevel: 32,
        types: [TypesEnum.water],
        height: '1.0 m',
        weight: '22.5 kg ',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Wartortle.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'When tapped, this Pokémon will pull in its head, but its tail will still stick out a little bit. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 9,
        name: 'Blastoise',
        types: [TypesEnum.water],
        height: '1.6m',
        weight: '85.5 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Blastoise.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Once it takes aim at its enemy, it blasts out water with even more force than a fire hose. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 10,
        name: 'Caterpie',
        evolutionLevel: 7,
        types: [TypesEnum.bug],
        height: '0.3 m',
        weight: '2.9 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Caterpie.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If you touch the feeler on top of its head, it will release a horrible stink to protect itself. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 11,
        name: 'Metapod',
        evolutionLevel: 10,
        types: [TypesEnum.bug],
        height: '0.7 m',
        weight: '9.9 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Metapod.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Hardens its shell to protect itself. However, a large impact may cause it to pop out of its shell. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 12,
        name: 'Butterfree',
        types: [TypesEnum.bug],
        height: '1.1 m',
        weight: '32.0 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Butterfree.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Its wings, covered with poisonous powders, repel water. This allows it to fly in the rain. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 13,
        name: 'Weedle',
        evolutionLevel: 7,
        types: [TypesEnum.bug],
        height: '0.3 m',
        weight: '3.2 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Weedle.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 14,
        name: 'Kakuna',
        evolutionLevel: 10,
        types: [TypesEnum.bug],
        height: '0.6 m',
        weight: '10.0 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Kakuna.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 15,
        name: 'Beedrill',
        types: [TypesEnum.bug],
        height: '1.0 m',
        weight: '29.5 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Beedrill.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'It has 3 poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 16,
        name: 'Pidgey',
        evolutionLevel: 18,
        types: [TypesEnum.flying],
        height: '0.3 m',
        weight: '1.8 kg',
        color: [ColorEnum.flyingColor],
        img: '../../assets/images/Pidgey.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Very docile. If attacked, it will often kick up sand to protect itself rather than fight back. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 17,
        name: 'Pidgeotto',
        evolutionLevel: 36,
        types: [TypesEnum.flying],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [ColorEnum.flyingColor],
        img: '../../assets/images/Pidgeotto.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon is full of vitality. It constantly flies around its large territory in search of prey. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 18,
        name: 'Pidgeot',
        types: [TypesEnum.flying],
        height: '1.5 m',
        weight: '39.5 kg',
        color: [ColorEnum.flyingColor],
        img: '../../assets/images/Pidgeot.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 19,
        name: 'Rattata',
        evolutionLevel: 20,
        types: [TypesEnum.normal],
        height: '0.3 m',
        weight: '3.5 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Rattata.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Will chew on anything with its fangs. If you see one, it is certain that 40 more live in the area. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 20,
        name: 'Raticate',
        types: [TypesEnum.normal],
        height: '0.7 m',
        weight: '18.5 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Raticate.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 21,
        name: 'Spearow',
        evolutionLevel: 20,
        types: [TypesEnum.normal, TypesEnum.flying],
        height: '0.3 m',
        weight: '2.0 kg',
        color: [ColorEnum.normalColor, ColorEnum.flyingColor],
        img: '../../assets/images/Spearow.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Inept at flying high. However, it can fly around very fast to protect its territory. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 22,
        name: 'Fearow',
        types: [TypesEnum.normal, TypesEnum.flying],
        height: '1.2 m',
        weight: '38.0 kg',
        color: [ColorEnum.normalColor, ColorEnum.flyingColor],
        img: '../../assets/images/Fearow.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 23,
        name: 'Ekans',
        evolutionLevel: 22,
        types: [TypesEnum.poison],
        height: '2.0 m',
        weight: '6.9 kg',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Ekans.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 24,
        name: 'Arbok',
        types: [TypesEnum.poison],
        height: '3.5 m',
        weight: '65.0 kg',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Arbok.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'The frightening patterns on its belly have been studied. Six variations have been confirmed. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 25,
        name: 'Pikachu',
        stone: [StoneEnum.thunder],
        types: [TypesEnum.electric],
        height: '0.4 m',
        weight: '6.0 kg',
        color: [ColorEnum.electricColor],
        img: '../../assets/images/Pikachu.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It keeps its tail raised to monitor its surroundings. If you yank its tail, it will try to bite you. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 26,
        name: 'Raichu',
        types: [TypesEnum.electric],
        height: '0.8 m',
        weight: '30.0 kg',
        color: [ColorEnum.electricColor],
        img: '../../assets/images/Raichu.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'When electricity builds up inside its body, it becomes feisty. It also glows in the dark. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 27,
        name: 'Sandshrew',
        evolutionLevel: 22,
        types: [TypesEnum.ground],
        height: '0.6 m',
        weight: '12.0 kg ',
        color: [ColorEnum.groundColor],
        img: '../../assets/images/Sandshrew.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Its body is dry. When it gets cold at night, its hide is said to become coated with a fine dew. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 28,
        name: 'Sandslash',
        types: [TypesEnum.ground],
        height: '1.0 m',
        weight: '29.5 kg ',
        color: [ColorEnum.groundColor],
        img: '../../assets/images/Sandslash.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'It is skilled at slashing enemies with its claws. If broken, they start to grow back in a day. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 29,
        name: 'Nidoran♀',
        evolutionLevel: 16,
        types: [TypesEnum.poison],
        height: '0.4 m',
        weight: '7.0 kg',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Nidoran♀.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'A mild-mannered Pokémon that does not like to fight. Beware, its small horns secrete venom. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 30,
        name: 'Nidorina',
        stone: [StoneEnum.moon],
        types: [TypesEnum.poison],
        height: '0.7 m',
        weight: '6.9 kg',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Nidorina.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'When resting deep in its burrow, its thorns always retract. This is proof that it is relaxed. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 31,
        name: 'Nidoqueen',
        types: [TypesEnum.poison, TypesEnum.ground],
        height: '1.3 m',
        weight: '60.0 kg',
        color: [ColorEnum.poisonColor, ColorEnum.groundColor],
        img: '../../assets/images/Nidoqueen.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Tough scales cover the sturdy body of this Pokémon. It appears that the scales grow in cycles. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 32,
        name: 'Nidoran♂',
        evolutionLevel: 16,
        types: [TypesEnum.poison],
        height: '0.5 m',
        weight: '9.0 kg',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Nidoran♂.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its large ears are always kept upright. If it senses danger, it will attack with a poisonous sting. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 33,
        name: 'Nidorino',
        stone: [StoneEnum.moon],
        types: [TypesEnum.poison],
        height: '0.9 m',
        weight: '19.5 kg',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Nidorino.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its horns contain venom. If they are stabbed into an enemy, the impact makes the poison leak out. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 34,
        name: 'Nidoking',
        types: [TypesEnum.poison, TypesEnum.poison],
        height: '1.4 m',
        weight: '62.0 kg',
        color: [ColorEnum.poisonColor, ColorEnum.groundColor],
        img: '../../assets/images/Nidoking.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its steel-like hide adds to its powerful tackle. Its horns are so hard, they can pierce a diamond. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 35,
        name: 'Clefairy',
        stone: [StoneEnum.moon],
        types: [TypesEnum.fairy],
        height: '0.6 m',
        weight: '7.5 kg ',
        color: [ColorEnum.fairyColor],
        img: '../../assets/images/Clefairy.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Adored for their cute looks and playfulness. They are thought to be rare, as they do not appear often. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 36,
        name: 'Clefable',
        types: [TypesEnum.fairy],
        height: '1.3 m',
        weight: '40.0 kg ',
        color: [ColorEnum.fairyColor],
        img: '../../assets/images/Clefable.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'They appear to be very protective of their own world. It is a kind of fairy, rarely seen by people. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 37,
        name: 'Vulpix',
        stone: [StoneEnum.fire],
        types: [TypesEnum.fire],
        height: '0.6 m',
        weight: '9.9 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Vulpix.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Both its fur and its tails are beautiful. As it grows, the tails split and form more tails. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 38,
        name: 'Ninetales',
        types: [TypesEnum.fire],
        height: '1.1 m',
        weight: '19.9 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Ninetales.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'According to an enduring legend, 9 noble saints were united and reincarnated as this Pokémon. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 39,
        name: 'Jigglypuff',
        stone: [StoneEnum.moon],
        types: [TypesEnum.normal, TypesEnum.fairy],
        height: '0.5 m',
        weight: '5.5 kg',
        color: [ColorEnum.normalColor, ColorEnum.fairyColor],
        img: '../../assets/images/Jigglypuff.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Uses its alluring eyes to enrapture its foe. It then sings a pleasing melody that lulls the foe to sleep. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 40,
        name: 'Wigglypuff',
        types: [TypesEnum.normal, TypesEnum.fairy],
        height: '1.0 m',
        weight: '12.0 kg',
        color: [ColorEnum.normalColor, ColorEnum.fairyColor],
        img: '../../assets/images/Wigglypuff.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Its body is full of elasticity. By inhaling deeply, it can continue to inflate itself without limit. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 41,
        name: 'Zubat',
        evolutionLevel: 22,
        types: [TypesEnum.poison, TypesEnum.flying],
        height: '0.8 m',
        weight: '7.5 kg',
        color: [ColorEnum.poisonColor, ColorEnum.flyingColor],
        img: '../../assets/images/Zubat.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Emits ultrasonic cries while it flies. They act as a sonar used to check for objects in its way. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 42,
        name: 'Golbat',
        types: [TypesEnum.poison, TypesEnum.flying],
        height: '1.6 m',
        weight: '55.0 kg',
        color: [ColorEnum.poisonColor, ColorEnum.flyingColor],
        img: '../../assets/images/Golbat.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'It attacks in a stealthy manner, without warning. Its sharp fangs are used to bite and suck blood. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 43,
        name: 'Oddish',
        evolutionLevel: 21,
        types: [TypesEnum.grass, TypesEnum.poison],
        height: '0.5 m',
        weight: '5.4 kg ',
        color: [ColorEnum.grassColor, ColorEnum.poisonColor],
        img: '../../assets/images/Oddish.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'It may be mistaken for a clump of weeds. If you try to yank it out of the ground, it shrieks horribly. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 44,
        name: 'Gloom',
        stone: [StoneEnum.leaf],
        types: [TypesEnum.grass, TypesEnum.poison],
        height: '0.8 m',
        weight: '8.6 kg ',
        color: [ColorEnum.grassColor, ColorEnum.poisonColor],
        img: '../../assets/images/Gloom.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'Smells incredibly foul! However, around 1 out of 1,000 people enjoy sniffing its nose-bending stink. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 45,
        name: 'Vileplume',
        types: [TypesEnum.grass, TypesEnum.poison],
        height: '1.2 m',
        weight: '18.6 kg',
        color: [ColorEnum.grassColor, ColorEnum.poisonColor],
        img: '../../assets/images/Vileplume.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Flaps its broad flower petals to scatter its poisonous pollen. The flapping sound is very loud. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 46,
        name: 'Paras',
        evolutionLevel: 24,
        types: [TypesEnum.bug, TypesEnum.grass],
        height: '0.3 m',
        weight: '5.4 kg',
        color: [ColorEnum.bugColor, ColorEnum.grassColor],
        img: '../../assets/images/Paras.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 47,
        name: 'Parasect',
        types: [TypesEnum.bug, TypesEnum.grass],
        height: '1.0 m',
        weight: '29.5 kg',
        color: [ColorEnum.bugColor, ColorEnum.grassColor],
        img: '../../assets/images/Parasect.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'The bug host is drained of energy by the mushrooms on its back. They appear to do all the thinking. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 48,
        name: 'Venonat',
        evolutionLevel: 31,
        types: [TypesEnum.bug, TypesEnum.poison],
        height: '1.0 m',
        weight: '30.0 kg',
        color: [ColorEnum.bugColor, ColorEnum.poisonColor],
        img: '../../assets/images/Venonat.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Its large eyes act as radars. In a bright place, you can see that they are clusters of many tiny eyes. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 49,
        name: 'Venomoth',
        types: [TypesEnum.bug, TypesEnum.poison],
        height: '1.5 m',
        weight: '12.5 kg',
        color: [ColorEnum.bugColor, ColorEnum.poisonColor],
        img: '../../assets/images/Venomoth.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The powdery scales on its wings are hard to remove. They also contain poison that leaks out on contact. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 50,
        name: 'Diglett',
        evolutionLevel: 26,
        types: [TypesEnum.ground],
        height: '0.2 m',
        weight: '0.8 kg ',
        color: [ColorEnum.groundColor],
        img: '../../assets/images/Diglett.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'It prefers dark places. It spends most of its time underground, though it may pop up in caves. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 51,
        name: 'Dugtrio',
        types: [TypesEnum.ground],
        height: '0.7 m',
        weight: '33.3 kg ',
        color: [ColorEnum.groundColor],
        img: '../../assets/images/Dugtrio.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'A team of triplets that can burrow over 60 MPH. Due to this, some people think it\'s an earthquake. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 52,
        name: 'Meowth',
        evolutionLevel: 28,
        types: [TypesEnum.normal],
        height: '0.4 m',
        weight: '4.2 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Meowth.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Appears to be more active at night. It loves round and shiny things. It can\'t stop from picking them up. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 53,
        name: 'Persian',
        types: [TypesEnum.normal],
        height: '1.0 m',
        weight: '32.0 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Persian.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'The gem in its forehead glows on its own! It walks with all the grace and elegance of a proud queen. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 54,
        name: 'Psyduck',
        evolutionLevel: 33,
        types: [TypesEnum.water],
        height: '0.8 m',
        weight: '19.6 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Psyduck.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Always tormented by headaches. It uses psychic powers, but it is not known if it intends to do so. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 55,
        name: 'Golduck',
        types: [TypesEnum.water],
        height: '1.7 m',
        weight: '76.6 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Golduck.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Its slim and long limbs end in broad flippers. They are used for swimming gracefully in lakes. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 56,
        name: 'Mankey',
        evolutionLevel: 28,
        types: [TypesEnum.fighting],
        height: '0.5 m',
        weight: '28.0 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Mankey.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 57,
        name: 'Primeape',
        types: [TypesEnum.fighting],
        height: '1.0 m',
        weight: '32.0 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Primeape.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'It stops being angry only when nobody else is around. To view this moment is very difficult. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 58,
        name: 'Growlithe',
        stone: [StoneEnum.fire],
        types: [TypesEnum.fire],
        height: '0.7 m',
        weight: '19.0 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Growlithe.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'A Pokémon with a friendly nature. However, it will bark fiercely at anything invading its territory. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 59,
        name: 'Arcanine',
        types: [TypesEnum.fire],
        height: '1.9 m',
        weight: '155.0 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Arcanine.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'A legendary Pokémon in China. Many people are charmed by its grace and beauty while running. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 60,
        name: 'Poliwag',
        evolutionLevel: 25,
        types: [TypesEnum.water],
        height: '0.6 m',
        weight: '12.4 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Poliwag.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'The direction of the spiral on the belly differs by area. It is more adept at swimming than walking. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 61,
        name: 'Poliwhirl',
        stone: [StoneEnum.water],
        evolutionLevel: 16,
        types: [TypesEnum.water],
        height: '1.0 m',
        weight: '20.0 kg ',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Poliwhirl.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Under attack, it uses its belly spiral to put the foe to sleep. It then makes its escape. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 62,
        name: 'Poliwrath',
        types: [TypesEnum.water, TypesEnum.fighting],
        height: '1.3 m',
        weight: '54.0 kg ',
        color: [ColorEnum.waterColor, ColorEnum.fightingColor],
        img: '../../assets/images/Poliwrath.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'Swims powerfully using all the muscles in its body. It can even overtake champion swimmers. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 63,
        name: 'Abra',
        evolutionLevel: 16,
        types: [TypesEnum.psychic],
        height: '0.9 m',
        weight: '19.5 kg',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Abra.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Sleeps 18 hours a day. If it senses danger, it will teleport itself to safety even as it sleeps. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 64,
        name: 'Kadabra',
        exchange: true,
        types: [TypesEnum.psychic],
        height: '1.3 m',
        weight: '56.5 kg',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Kadabra.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Many odd things happen if this Pokémon is close by. For example, it makes clocks run backwards. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 65,
        name: 'Alakazam',
        types: [TypesEnum.psychic],
        height: '1.5 m',
        weight: '48.0 kg',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Alakazam.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'A Pokémon that can memorize anything. It never forgets what it learns—that\'s why this Pokémon is smart. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 66,
        name: 'Machop',
        evolutionLevel: 28,
        types: [TypesEnum.fighting],
        height: '0.8 m',
        weight: '19.5 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Machop.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Very powerful in spite of its small size. Its mastery of many types of martial arts makes it very tough. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 67,
        name: 'Machoke',
        exchange: true,
        types: [TypesEnum.fighting],
        height: '1.5 m',
        weight: '70.5 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Machoke.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'The belt around its waist holds back its energy. Without it, this Pokémon would be unstoppable. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 68,
        name: 'Machamp',
        types: [TypesEnum.fighting],
        height: '1.6 m',
        weight: '130.0 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Machamp.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'One arm alone can move mountains. Using all four arms, this Pokémon fires off awesome punches. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 69,
        name: 'Bellsprout',
        evolutionLevel: 21,
        types: [TypesEnum.grass, TypesEnum.poison],
        height: '0.7 m',
        weight: '4.0 kg',
        color: [ColorEnum.grassColor, ColorEnum.poisonColor],
        img: '../../assets/images/Bellsprout.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Prefers hot and humid places. It ensnares tiny insects with its vines and devours them. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 70,
        name: 'Weepinbell',
        stone: [StoneEnum.leaf],
        types: [TypesEnum.grass, TypesEnum.poison],
        height: '1.0 m',
        weight: '6.4 kg',
        color: [ColorEnum.grassColor, ColorEnum.poisonColor],
        img: '../../assets/images/Weepinbell.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'When hungry, it swallows anything that moves. Its hapless prey is melted inside by strong acids. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 71,
        name: 'Victreebel',
        types: [TypesEnum.grass, TypesEnum.poison],
        height: '1.7 m',
        weight: '15.5 kg',
        color: [ColorEnum.grassColor, ColorEnum.poisonColor],
        img: '../../assets/images/Victreebel.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Lures prey with the sweet aroma of honey. Swallowed whole, the prey is melted in a day, bones and all. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 72,
        name: 'Tentacool',
        evolutionLevel: 30,
        types: [TypesEnum.water, TypesEnum.poison],
        height: '0.9 m',
        weight: '45.5 kg',
        color: [ColorEnum.waterColor, ColorEnum.poisonColor],
        img: '../../assets/images/Tentacool.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'It can sometimes be found all dry and shriveled up on a beach. Toss it back into the sea to revive it. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 73,
        name: 'Tentacruel',
        types: [TypesEnum.water, TypesEnum.poison],
        height: '1.6 m',
        weight: '55.0 kg',
        color: [ColorEnum.waterColor, ColorEnum.poisonColor],
        img: '../../assets/images/Tentacruel.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Its 80 tentacles can stretch and contract freely. They wrap around prey and weaken it with poison. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 74,
        name: 'Geodude',
        evolutionLevel: 25,
        types: [TypesEnum.rock, TypesEnum.ground],
        height: '0.4 m',
        weight: '20.0 kg',
        color: [ColorEnum.rockColor, ColorEnum.groundColor],
        img: '../../assets/images/Geodude.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Commonly found near mountain trails, etc. If you step on one by accident, it gets angry. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 75,
        name: 'Graveler',
        exchange: true,
        types: [TypesEnum.rock, TypesEnum.ground],
        height: '1.0 m',
        weight: '105.0 kg',
        color: [ColorEnum.rockColor, ColorEnum.groundColor],
        img: '../../assets/images/Graveler.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Often seen rolling down mountain trails. Obstacles are just things to roll straight over, not avoid. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 76,
        name: 'Golem',
        types: [TypesEnum.rock, TypesEnum.ground],
        height: '1.4 m',
        weight: '300.0 kg',
        color: [ColorEnum.rockColor, ColorEnum.groundColor],
        img: '../../assets/images/Golem.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it\'s exposed to air. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 77,
        name: 'Ponyta',
        evolutionLevel: 40,
        types: [TypesEnum.fire],
        height: '1.0 m',
        weight: '30.0 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Ponyta.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Capable of jumping incredibly high. Its hooves and sturdy legs absorb the impact of a hard landing. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 78,
        name: 'Rapidash',
        types: [TypesEnum.fire],
        height: '1.7 m',
        weight: '95.0 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Rapidash.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Just loves to run. If it sees something faster than itself, it will give chase at top speed. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 79,
        name: 'Slowpoke',
        evolutionLevel: 37,
        types: [TypesEnum.water, TypesEnum.psychic],
        height: '1.2 m',
        weight: '36.0 kg',
        color: [ColorEnum.waterColor, ColorEnum.psychicColor],
        img: '../../assets/images/Slowpoke.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Incredibly slow and sluggish. It is quite content to loll about without worrying about the time. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 80,
        name: 'Slowbro',
        types: [TypesEnum.water, TypesEnum.psychic],
        height: '1.6 m',
        weight: '78.5 kg',
        color: [ColorEnum.waterColor, ColorEnum.psychicColor],
        img: '../../assets/images/Slowbro.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Lives lazily by the sea. If the Shellder on its tail comes off, it becomes a Slowpoke again. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 81,
        name: 'Magnemite',
        evolutionLevel: 30,
        types: [TypesEnum.electric, TypesEnum.steel],
        height: '0.3 m',
        weight: '6.0 kg ',
        color: [ColorEnum.electricColor, ColorEnum.steelColor],
        img: '../../assets/images/Magnemite.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'It is born with the ability to defy gravity. It floats in air on powerful electromagnetic waves. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 82,
        name: 'Magneton',
        types: [TypesEnum.electric, TypesEnum.steel],
        height: '1.0 m',
        weight: '60.0 kg ',
        color: [ColorEnum.electricColor, ColorEnum.steelColor],
        img: '../../assets/images/Magneton.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'Generates strange radio signals. It raises the temperature by 3.6F degrees within 3,300 feet. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 83,
        name: 'Farfetch\'d',
        types: [TypesEnum.normal, TypesEnum.flying],
        height: '0.8 m',
        weight: '15.0 kg',
        color: [ColorEnum.normalColor, ColorEnum.flyingColor],
        img: '../../assets/images/Farfetch\'d.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Lives where reedy plants grow. They are rarely seen, so it\'s thought their numbers are decreasing. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 84,
        name: 'Doduo',
        evolutionLevel: 31,
        types: [TypesEnum.normal, TypesEnum.flying],
        height: '1.4 m',
        weight: '39.2 kg',
        color: [ColorEnum.normalColor, ColorEnum.flyingColor],
        img: '../../assets/images/Doduo.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 85,
        name: 'Dodrio',
        types: [TypesEnum.normal, TypesEnum.flying],
        height: '1.8 m',
        weight: '85.2 kg',
        color: [ColorEnum.normalColor, ColorEnum.flyingColor],
        img: '../../assets/images/Dodrio.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'One of Doduo\'s 2 heads splits to form a unique species. It runs close to 40 MPH in prairies. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 86,
        name: 'Seel',
        evolutionLevel: 34,
        types: [TypesEnum.water],
        height: '1.1 m',
        weight: '90.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Seel.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Loves freezing cold conditions. Relishes swimming in a frigid climate of around 14F degrees. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 87,
        name: 'Dewgong',
        types: [TypesEnum.water, TypesEnum.ice],
        height: '1.7 m',
        weight: '120.0 kg',
        color: [ColorEnum.waterColor, ColorEnum.iceColor],
        img: '../../assets/images/Dewgong.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its entire body is a snowy-white. Unharmed by even intense cold, it swims powerfully in icy waters. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 88,
        name: 'Grimer',
        evolutionLevel: 38,
        types: [TypesEnum.poison],
        height: '0.9 m',
        weight: '30.0 kg ',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Grimer.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Made of hardened sludge. It smells too putrid to touch. Even weeds won\'t grow in its path. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 89,
        name: 'Muk',
        types: [TypesEnum.poison],
        height: '1.2 m',
        weight: '30.0 kg ',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Muk.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'Smells so awful, it can cause fainting. Through degeneration, it lost its sense of smell. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 90,
        name: 'Shellder',
        stone: [StoneEnum.water],
        types: [TypesEnum.water],
        height: '0.3 m',
        weight: '4.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Shellder.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'The shell can withstand any attack. However, when it is open, the tender body is exposed. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 91,
        name: 'Cloyster',
        types: [TypesEnum.water, TypesEnum.ice],
        height: '1.5 m',
        weight: '132.5 kg',
        color: [ColorEnum.waterColor, ColorEnum.iceColor],
        img: '../../assets/images/Cloyster.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'For protection, it uses its harder-than-diamonds shell. It also shoots spikes from the shell. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 92,
        name: 'Gastly',
        evolutionLevel: 25,
        types: [TypesEnum.ghost, TypesEnum.poison],
        height: '1.3 m',
        weight: '0.1 kg',
        color: [ColorEnum.ghostColor, ColorEnum.poisonColor],
        img: '../../assets/images/Gastly.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Said to appear in decrepit, deserted buildings. It has no real shape as it appears to be made of a gas. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 93,
        name: 'Haunter',
        exchange: true,
        types: [TypesEnum.ghost, TypesEnum.poison],
        height: '1.6 m',
        weight: '0.1 kg',
        color: [ColorEnum.ghostColor, ColorEnum.poisonColor],
        img: '../../assets/images/Haunter.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'By licking, it saps the victim\'s life. It causes shaking that won\'t stop until the victim\'s demise. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 94,
        name: 'Gengar',
        types: [TypesEnum.ghost, TypesEnum.poison],
        height: '1.5 m',
        weight: '40.5 kg',
        color: [ColorEnum.ghostColor, ColorEnum.poisonColor],
        img: '../../assets/images/Gengar.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'A Gengar is close by if you feel a sudden chill. It may be trying to lay a curse on you. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 95,
        name: 'Onix',
        types: [TypesEnum.rock],
        height: '8.8 m',
        weight: '210.0 kg ',
        color: [ColorEnum.rockColor],
        img: '../../assets/images/Onix.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Burrows at high speed in search of food. The tunnels it leaves are used as homes by Diglett. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 96,
        name: 'Drowzee',
        evolutionLevel: 26,
        types: [TypesEnum.psychic],
        height: '1.0 m',
        weight: '32.4 kg ',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Drowzee.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'If you sleep by it all the time, it will sometimes show you dreams it has eaten in the past. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 97,
        name: 'Hypno',
        types: [TypesEnum.psychic],
        height: '1.6 m',
        weight: '75.6 kg',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Hypno.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 98,
        name: 'Krabby',
        evolutionLevel: 28,
        types: [TypesEnum.water],
        height: '0.4 m',
        weight: '6.5 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Krabby.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Its pincers are superb weapons. They sometimes break off during battle, but they grow back fast. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 99,
        name: 'Kingler',
        types: [TypesEnum.water],
        height: '1.3 m',
        weight: '60.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Kingler.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'One claw grew massively and as hard as steel. It has 10,000-HP strength. However, it is too heavy. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 100,
        name: 'Voltorb',
        evolutionLevel: 30,
        types: [TypesEnum.electric],
        height: '0.5 m',
        weight: '10.4 kg',
        color: [ColorEnum.electricColor],
        img: '../../assets/images/Voltorb.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 101,
        name: 'Electrode',
        types: [TypesEnum.electric],
        height: '1.2 m',
        weight: '66.6 kg',
        color: [ColorEnum.electricColor],
        img: '../../assets/images/Electrode.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 102,
        name: 'Exeggcute',
        stone: [StoneEnum.leaf],
        evolutionLevel: 16,
        types: [TypesEnum.grass, TypesEnum.psychic],
        height: '0.4 m',
        weight: '2.5 kg ',
        color: [ColorEnum.grassColor, ColorEnum.psychicColor],
        img: '../../assets/images/Exeggcute.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'The heads attract each other and spin around. There must be 6 heads for it to maintain balance. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 103,
        name: 'Exeggcutor',
        types: [TypesEnum.grass, TypesEnum.psychic],
        height: '2.0 m',
        weight: '120.0 kg ',
        color: [ColorEnum.grassColor, ColorEnum.psychicColor],
        img: '../../assets/images/Exeggcutor.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Its cries are very noisy. This is because each of the three heads thinks about whatever it likes. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 104,
        name: 'Cubone',
        evolutionLevel: 28,
        types: [TypesEnum.ground],
        height: '0.4 m',
        weight: '6.5 kg',
        color: [ColorEnum.groundColor],
        img: '../../assets/images/Cubone.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Wears the skull of its deceased mother. Its cries echo inside the skull and come out as a sad melody. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 105,
        name: 'Marowak',
        types: [TypesEnum.ground],
        height: '1.0 m',
        weight: '45.0 kg',
        color: [ColorEnum.groundColor],
        img: '../../assets/images/Marowak.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Small and weak, this Pokémon is adept with its Bone Club. It has grown more vicious over the ages. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 106,
        name: 'Hitmonlee',
        types: [TypesEnum.fighting],
        height: '1.5 m',
        weight: '49.8 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Hitmonlee.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'When kicking, the sole of its foot turns as hard as a diamond on impact and destroys its enemy. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 107,
        name: 'Hitmonchan',
        types: [TypesEnum.fighting],
        height: '1.4 m',
        weight: '50.2 kg',
        color: [ColorEnum.fightingColor],
        img: '../../assets/images/Hitmonchan.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Punches in corkscrew fashion. It can punch its way through a concrete wall in the same way as a drill. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 108,
        name: 'Lickitung',
        types: [TypesEnum.normal],
        height: '1.2 m',
        weight: '65.5 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Lickitung.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its tongue spans almost 7 feet and moves more freely than its forelegs. Its licks can cause paralysis. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 109,
        name: 'Koffing',
        evolutionLevel: 35,
        types: [TypesEnum.poison],
        height: '0.6 m',
        weight: '1.0 kg ',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Koffing.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'In hot places, its internal gases could expand and explode without any warning. Be very careful! ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 110,
        name: 'Weezing',
        types: [TypesEnum.poison],
        height: '1.2 m',
        weight: '9.5 kg ',
        color: [ColorEnum.poisonColor],
        img: '../../assets/images/Weezing.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'It lives and grows by absorbing dust, germs, and poison gases that are contained in toxic waste and garbage. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 111,
        name: 'Rhyhorn',
        evolutionLevel: 42,
        types: [TypesEnum.ground, TypesEnum.rock],
        height: '1.0 m',
        weight: '115.0 kg',
        color: [ColorEnum.groundColor, ColorEnum.rockColor],
        img: '../../assets/images/Rhyhorn.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'A Pokémon with a one-track mind. Once it charges, it won\'t stop running until it falls asleep. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 112,
        name: 'Rhydon',
        types: [TypesEnum.ground, TypesEnum.rock],
        height: '1.9 m',
        weight: '120.0 kg',
        color: [ColorEnum.groundColor, ColorEnum.rockColor],
        img: '../../assets/images/Rhydon.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Walks on its hind legs. Shows signs of intelligence. Its armor-like hide even repels molten lava. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 113,
        name: 'Chansey',
        types: [TypesEnum.normal],
        height: '1.1 m',
        weight: '34.6 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Chansey.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'A gentle and kind-hearted Pokémon that shares its nutritious eggs if it sees an injured Pokémon. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 114,
        name: 'Tangela',
        types: [TypesEnum.grass],
        height: '1.0 m',
        weight: '35.0 kg',
        color: [ColorEnum.grassColor],
        img: '../../assets/images/Tangela.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Its identity is obscured by masses of thick, blue vines. The vines are said to never stop growing. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 115,
        name: 'Kangaskhan',
        types: [TypesEnum.normal],
        height: '2.2 m',
        weight: '80.0 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Kangaskhan.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Raises its young in its belly pouch. Won\'t run from any fight to keep its young protected. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 116,
        name: 'Horsea',
        evolutionLevel: 32,
        types: [TypesEnum.water],
        height: '0.4 m',
        weight: '8.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Horsea.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'If it senses any danger, it will vigorously spray water or a special type of ink from its mouth.  ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 117,
        name: 'Seadra',
        evolutionLevel: 33,
        types: [TypesEnum.water],
        height: '0.6 m',
        weight: '15.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Seadra.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Touching the back fin causes numbness. It hooks its tail to coral to stay in place while sleeping. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 118,
        name: 'Goldeen',
        evolutionLevel: 33,
        types: [TypesEnum.water],
        height: '0.6 m',
        weight: '15.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Goldeen.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'When it is time for them to lay eggs, they can be seen swimming up rivers and falls in large groups. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 119,
        name: 'Seaking',
        types: [TypesEnum.water],
        height: '1.3 m',
        weight: '39.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Seaking.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'It is the male\'s job to make a nest by carving out boulders in a stream using the horn on its head. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 120,
        name: 'Staryu',
        stone: [StoneEnum.water],
        types: [TypesEnum.water],
        height: '0.8 m',
        weight: '34.5 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Staryu.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'As long as the center section is unharmed, it can grow back fully even if it is chopped to bits. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 121,
        name: 'Starmie',
        types: [TypesEnum.water, TypesEnum.psychic],
        height: '1.1 m',
        weight: '80.0 kg',
        color: [ColorEnum.waterColor, ColorEnum.psychicColor],
        img: '../../assets/images/Starmie.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'The center section is named the core. People think it is communicating when it glows in 7 colors. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 122,
        name: 'Mr. Mime',
        types: [TypesEnum.psychic, TypesEnum.fairy],
        height: '1.3 m',
        weight: '54.5 kg',
        color: [ColorEnum.psychicColor, ColorEnum.fairyColor],
        img: '../../assets/images/MrMime.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'Always practices its pantomime act. It makes enemies believe something exists that really doesn\'t. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 123,
        name: 'Scyther',
        types: [TypesEnum.bug, TypesEnum.flying],
        height: '1.5 m',
        weight: '56.0 kg',
        color: [ColorEnum.bugColor, ColorEnum.flyingColor],
        img: '../../assets/images/Scyther.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Leaps out of tall grass and slices prey with its scythes. The movement looks like that of a ninja. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 124,
        name: 'Jynx',
        types: [TypesEnum.ice, TypesEnum.psychic],
        height: '1.4 m',
        weight: '40.6 kg',
        color: [ColorEnum.iceColor, ColorEnum.psychicColor],
        img: '../../assets/images/Jynx.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Appears to move to a rhythm of its own, as if it were dancing. It wiggles its hips as it walks. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 125,
        name: 'Electabuzz',
        types: [TypesEnum.electric],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [ColorEnum.electricColor],
        img: '../../assets/images/Electabuzz.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'If a major power outage occurs, it is certain that this Pokémon has eaten electricity at a power plant. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 126,
        name: 'Magmar',
        types: [TypesEnum.fire],
        height: '1.3 m',
        weight: '44.5 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Magmar.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'Born in an active volcano. Its body is always cloaked in flames, so it looks like a big ball of fire. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 127,
        name: 'Pinsir',
        types: [TypesEnum.bug],
        height: '1.5 m',
        weight: '55.0 kg',
        color: [ColorEnum.bugColor],
        img: '../../assets/images/Pinsir.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Grips its prey in its pincers and squeezes hard! It can\'t move if it\'s cold, so it lives in warm places. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 128,
        name: 'Tauros',
        types: [TypesEnum.normal],
        height: '1.4 m',
        weight: '88.4 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Tauros.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'A rowdy Pokémon with a lot of stamina. Once running, it won\'t stop until it hits something. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 129,
        name: 'Magikarp',
        evolutionLevel: 20,
        types: [TypesEnum.water],
        height: '0.9 m',
        weight: '10.0 kg ',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Magikarp.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'Famous for being very unreliable. It can be found swimming in seas, lakes, rivers and shallow puddles. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 130,
        name: 'Gyarados',
        types: [TypesEnum.water, TypesEnum.flying],
        height: '6.5 m',
        weight: '235.0 kg ',
        color: [ColorEnum.waterColor, ColorEnum.flyingColor],
        img: '../../assets/images/Gyarados.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'Brutally vicious and enormously destructive. Known for totally destroying cities in ancient times. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 131,
        name: 'Lapras',
        types: [TypesEnum.water, TypesEnum.ice],
        height: '2.5 m',
        weight: '220.0 kg',
        color: [ColorEnum.waterColor, ColorEnum.iceColor],
        img: '../../assets/images/Lapras.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'A gentle soul that can read the minds of people. It can ferry people across the sea on its back. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 132,
        name: 'Ditto',
        types: [TypesEnum.normal],
        height: '0.3 m',
        weight: '4.0 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Ditto.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'When it spots an enemy, its body transforms into an almost perfect copy of its opponent. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 133,
        name: 'Eevee',
        stone: [StoneEnum.water, StoneEnum.thunder, StoneEnum.fire],
        types: [TypesEnum.normal],
        height: '0.3 m',
        weight: '6.5 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Eevee.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'Its genetic code is unstable, so it could evolve in a variety of ways. There are only a few alive. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 134,
        name: 'Vaporeon',
        types: [TypesEnum.water],
        height: '1.0 m',
        weight: '29.0 kg',
        color: [ColorEnum.waterColor],
        img: '../../assets/images/Vaporeon.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its cell structure is similar to water molecules. It will melt away and become invisible in water. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 135,
        name: 'Jolteon',
        types: [TypesEnum.electric],
        height: '0.8 m',
        weight: '24.5 kg',
        color: [ColorEnum.electricColor],
        img: '../../assets/images/Jolteon.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'A sensitive Pokémon that easily becomes sad or angry. Every time its mood changes, it charges power. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 136,
        name: 'Flareon',
        types: [TypesEnum.fire],
        height: '0.9 m',
        weight: '25.0 kg',
        color: [ColorEnum.fireColor],
        img: '../../assets/images/Flareon.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'It has a flame chamber inside its body. It inhales, then blows out fire that is over 3,000F degrees. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 137,
        name: 'Porygon',
        evolutionLevel: 16,
        types: [TypesEnum.normal],
        height: '0.8 m',
        weight: '36.5 kg ',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Porygon.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'The only Pokémon people anticipate can fly into space. None has managed the feat yet, however. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 138,
        name: 'Omanyte',
        evolutionLevel: 40,
        types: [TypesEnum.rock, TypesEnum.water],
        height: '0.4 m',
        weight: '7.5 kg ',
        color: [ColorEnum.rockColor, ColorEnum.waterColor],
        img: '../../assets/images/Omanyte.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'An ancient Pokémon that was recovered from a fossil. It swims by cleverly twisting its 10 tentacles about. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 139,
        name: 'Omastar',
        types: [TypesEnum.rock, TypesEnum.water],
        height: '1.0 m',
        weight: '35.0 kg ',
        color: [ColorEnum.rockColor, ColorEnum.waterColor],
        img: '../../assets/images/Omastar.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'Sharp beaks ring its mouth. Its shell was too big for it to move freely, so it became extinct. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 140,
        name: 'Kabuto',
        types: [TypesEnum.rock, TypesEnum.water],
        height: '0.5 m',
        weight: '11.5 kg ',
        color: [ColorEnum.rockColor, ColorEnum.waterColor],
        img: '../../assets/images/Kabuto.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'A Pokémon that was recovered from a fossil. It uses the eyes on its back while hiding on the sea floor. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 141,
        name: 'Kabutops',
        types: [TypesEnum.rock, TypesEnum.water],
        height: '1.3 m',
        weight: '40.5 kg ',
        color: [ColorEnum.rockColor, ColorEnum.waterColor],
        img: '../../assets/images/Kabutops.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'A slim and fast swimmer. It slices its prey with its sharp sickles and drinks the body fluids. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 142,
        name: 'Aerodactyl',
        types: [TypesEnum.rock, TypesEnum.flying],
        height: '1.8 m',
        weight: '59.0 kg ',
        color: [ColorEnum.rockColor, ColorEnum.flyingColor],
        img: '../../assets/images/Aerodactyl.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'A savage Pokémon that died out in ancient times. It was resurrected using DNA taken from amber. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 143,
        name: 'Snorlax',
        types: [TypesEnum.normal],
        height: '2.1 m',
        weight: '460.0 kg',
        color: [ColorEnum.normalColor],
        img: '../../assets/images/Snorlax.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Will eat anything, even if the food happens to be a little moldy. It never gets an upset stomach. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 144,
        name: 'Articuno',
        types: [TypesEnum.ice, TypesEnum.flying],
        height: '1.7 m',
        weight: '55.4 kg ',
        color: [ColorEnum.iceColor, ColorEnum.flyingColor],
        img: '../../assets/images/Articuno.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'A legendary bird Pokémon. It freezes water that is contained in winter air and makes it snow. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
      {
        id: 145,
        name: 'Zapdos',
        types: [TypesEnum.electric, TypesEnum.flying],
        height: '1.6 m',
        weight: '52.6 kg ',
        color: [ColorEnum.electricColor, ColorEnum.flyingColor],
        img: '../../assets/images/Zapdos.png',
        audio: 'https://www.pokepedia.fr/images/6/6f/Cri_4_d_008.ogg',
        description: 'This legendary bird Pokémon is said to appear when the sky turns dark and lightning showers down. ',
        attacks: ['Tackle', 'Tail Whip', 'Water Gun', 'Withdraw']
      },
      {
        id: 146,
        name: 'Moltres',
        types: [TypesEnum.fire, TypesEnum.flying],
        height: '2.0 m',
        weight: '60.0 kg',
        color: [ColorEnum.fireColor, ColorEnum.flyingColor],
        img: '../../assets/images/Moltres.png',
        audio: 'https://www.pokepedia.fr/images/f/f9/Cri_4_d_017.ogg',
        description: 'A legendary bird Pokémon. As it flaps its blazing wings, even the night sky will turn red. ',
        attacks: ['Tackle', 'String Shot']
      },
      {
        id: 147,
        name: 'Dratini',
        evolutionLevel: 30,
        types: [TypesEnum.dragon],
        height: '1.8 m',
        weight: '3.3 kg',
        color: [ColorEnum.dragonColor],
        img: '../../assets/images/Dratini.png',
        audio: 'https://www.pokepedia.fr/images/4/4c/Cri_4_d_010.ogg',
        description: 'The existence of this mythical Pokémon was only recently confirmed by a fisherman who caught one. ',
        attacks: ['Gust', 'Sand-Attack', 'Quick Attack', 'Whirlwind']
      },
      {
        id: 148,
        name: 'Dragonair',
        evolutionLevel: 55,
        types: [TypesEnum.dragon],
        height: '1.1 m',
        weight: '30.0 kg',
        color: [ColorEnum.dragonColor],
        img: '../../assets/images/Dragonair.png',
        audio: 'https://www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg',
        description: 'According to a witness, its body was surrounded by a strange aura that gave it a mystical look. ',
        attacks: ['Tackle', 'Growl', 'Leech Seed', 'Vine Whip']
      },
      {
        id: 149,
        name: 'Dragonite',
        types: [TypesEnum.dragon, TypesEnum.flying],
        height: '2.2 m',
        weight: '210 kg',
        color: [ColorEnum.dragonColor, ColorEnum.flyingColor],
        img: '../../assets/images/Dragonite.png',
        audio: 'https://www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg',
        description: 'It is said that this Pokémon lives somewhere in the sea and that it flies. However, it is only a rumor. ',
        attacks: [' ThunderShock', 'Growl', ' Tail Whip', 'Thunder Wave']
      },
      {
        id: 150,
        name: 'Mewtwo',
        types: [TypesEnum.psychic],
        height: '2.0 m',
        weight: '122 kg',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Mewtwo.png',
        audio: 'https://www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg',
        description: 'Its DNA is almost the same as Mew\'s. However, its size and disposition are vastly different. ',
        attacks: ['Scratch', 'Growl', 'Ember', 'Leer']
      },
      {
        id: 151,
        name: 'Mew',
        types: [TypesEnum.psychic],
        height: '0.4 m',
        weight: '4.0 kg ',
        color: [ColorEnum.psychicColor],
        img: '../../assets/images/Mew.png',
        audio: 'https://www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg',
        description: 'When viewed through a microscope, this Pokémon\'s short, fine, delicate hair can be seen. ',
        attacks: ['Tackle', 'Tail Whip', 'Bubble', 'Water Gun']
      },
    ];
  }

  getDetailsPokemon(id: number) {
    return this.pokemonArray[id - 1];
  }

  getAllPokemons(): Observable<Array<Pokemon>> {
    return of(this.pokemonArray);
  }
}
