export enum TypesEnum {
  fire = 'fire',
  grass = 'grass',
  water = 'water',
  electric = 'electric',
  flying = 'flying',
  rock = 'rock',
  ghost = 'ghost',
  dark = 'dark',
  fighting = 'fighting',
  steel = 'steel',
  dragon = 'dragon',
  bug = 'bug',
  normal = 'normal',
  poison = 'poison',
  ground = 'ground',
  fairy = 'fairy',
  psychic = 'psychic',
  ice = 'ice'
}
